<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>



In [212]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.3'

# 데이터 연산

## 연산자 범용 함수

|||
|----|----|
|`add()` |덧셈 (+)|
|`sub()` | 뺄셈 (-)|
|`mul()` | 곱셈(\*)|
|`div()` | 몫 (/)|
|`mod()` | 나머지(//)|
|`pow()` | 지수 (\*\*)|



https://kongdols-room.tistory.com/126

### add()

In [122]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[4, 7, 7],
       [2, 5, 4],
       [2, 5, 5]])

In [123]:
a + a[0]

array([[ 8, 14, 14],
       [ 6, 12, 11],
       [ 6, 12, 12]])

In [124]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  4  7  7
1  2  5  4
2  2  5  5

In [125]:
df + df.iloc[0]

A   B   C
0  8  14  14
1  6  12  11
2  6  12  12

In [126]:
df.add(df.iloc[0])

A   B   C
0  8  14  14
1  6  12  11
2  6  12  12

###  `sub()`

In [127]:
a - a[0]

array([[ 0,  0,  0],
       [-2, -2, -3],
       [-2, -2, -2]])

In [128]:
df

A  B  C
0  4  7  7
1  2  5  4
2  2  5  5

In [129]:
df - df.iloc[0]

A  B  C
0  0  0  0
1 -2 -2 -3
2 -2 -2 -2

###### 컬럼 단위로 빼주기 위해서는~

`sub(axis=0) ` 을 사용해 준다. 

In [130]:
df.iloc[:, 0]

0    4
1    2
2    2
Name: A, dtype: int32

결과 값이 원하는대로 나오지 않는다. 

In [131]:
df - df.iloc[:, 0]

A   B   C   0   1   2
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN

axis=0 

In [132]:
df.sub(df.iloc[:,0], axis=0)

A  B  C
0  0  3  3
1  0  3  2
2  0  3  3

### mul()

상식-0-
* 축약
    - mul : multiply
    - mat : matrix 

In [133]:
a

array([[4, 7, 7],
       [2, 5, 4],
       [2, 5, 5]])

In [134]:
a[1]

array([2, 5, 4])

In [135]:
a * a[1]

array([[ 8, 35, 28],
       [ 4, 25, 16],
       [ 4, 25, 20]])

In [136]:
df * df.iloc[1]

A   B   C
0  8  35  28
1  4  25  16
2  4  25  20

axis=0

In [137]:
df.mul(df.A, axis=0)

A   B   C
0  16  28  28
1   4  10   8
2   4  10  10

###  div()

* div() / divide()
* truediv()
* floordiv() : 정수 환원

In [138]:
a

array([[4, 7, 7],
       [2, 5, 4],
       [2, 5, 5]])

In [139]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.5       , 0.71428571, 0.57142857],
       [0.5       , 0.71428571, 0.71428571]])

In [140]:
a / 0

<ipython-input-140-4f74cdd1c1e6>:1: RuntimeWarning: divide by zero encountered in true_divide
  a / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [141]:
df

A  B  C
0  4  7  7
1  2  5  4
2  2  5  5

In [142]:
df / df.iloc[0]

A         B         C
0  1.0  1.000000  1.000000
1  0.5  0.714286  0.571429
2  0.5  0.714286  0.714286

In [143]:
df.div(df['A'],axis=0)

A     B     C
0  1.0  1.75  1.75
1  1.0  2.50  2.00
2  1.0  2.50  2.50

In [144]:
df.truediv(df['A'],axis=0)

A     B     C
0  1.0  1.75  1.75
1  1.0  2.50  2.00
2  1.0  2.50  2.50

In [145]:
df.floordiv(df['A'],axis=0)

A  B  C
0  1  1  1
1  1  2  2
2  1  2  2

### mod()

In [146]:
a

array([[4, 7, 7],
       [2, 5, 4],
       [2, 5, 5]])

In [147]:
a % a[0]

array([[0, 0, 0],
       [2, 5, 4],
       [2, 5, 5]], dtype=int32)

In [148]:
df

A  B  C
0  4  7  7
1  2  5  4
2  2  5  5

In [149]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  2  5  4
2  2  5  5

In [150]:
df.mod(df.iloc[:,0], axis=0)

A  B  C
0  0  3  3
1  0  1  0
2  0  1  1

### pow()

In [151]:
a

array([[4, 7, 7],
       [2, 5, 4],
       [2, 5, 5]])

In [152]:
a ** a[0]

array([[   256, 823543, 823543],
       [    16,  78125,  16384],
       [    16,  78125,  78125]], dtype=int32)

In [153]:
df.pow(df.iloc[0])

A       B       C
0  256  823543  823543
1   16   78125   16384
2   16   78125   78125

In [154]:
df.pow(df.iloc[:,0], axis=0)

A     B     C
0  256  2401  2401
1    4    25    16
2    4    25    25

In [155]:
row = df.iloc[0, ::2]
row


A    4
C    7
Name: 0, dtype: int32

In [156]:
df

A  B  C
0  4  7  7
1  2  5  4
2  2  5  5

In [157]:
df - row

A   B    C
0  0.0 NaN  0.0
1 -2.0 NaN -3.0
2 -2.0 NaN -2.0

## 정렬(Sort)

1. sort_index() : axis= 0 , axis=1
2. sort_values() : by=['A'], by=['A','C']

In [158]:
s = pd.Series(range(5), index=['A', 'D', 'B', 'C', 'E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [159]:
s= s.sort_index()
s

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [160]:
df = pd.DataFrame(np.random.randint(1, 10, (4,4)),
                  columns=list('BDAC'),
                  index=[21, 11, 13, 44])
df

B  D  A  C
21  8  1  7  8
11  2  4  1  1
13  8  4  1  2
44  3  7  2  9

### sort_index()

In [161]:
df.sort_index()# default axis=0

B  D  A  C
11  2  4  1  1
13  8  4  1  2
21  8  1  7  8
44  3  7  2  9

컬럼이름으로 정렬하기 

In [162]:
df.sort_index(axis=1)

A  B  C  D
21  7  8  8  1
11  1  2  1  4
13  1  8  2  4
44  2  3  9  7

### sort_values()

In [163]:
s

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [164]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [165]:
df

B  D  A  C
21  8  1  7  8
11  2  4  1  1
13  8  4  1  2
44  3  7  2  9

In [166]:
df.iloc[:,1] = [1, 1, 2, 2]
df

B  D  A  C
21  8  1  7  8
11  2  1  1  1
13  8  2  1  2
44  3  2  2  9

In [167]:
df.sort_values(by=['D'])

B  D  A  C
21  8  1  7  8
11  2  1  1  1
13  8  2  1  2
44  3  2  2  9

In [168]:
df.sort_values(by=['D','A'])

B  D  A  C
11  2  1  1  1
21  8  1  7  8
13  8  2  1  2
44  3  2  2  9

In [169]:
df.sort_index(axis=1, ascending=False).sort_values(by=['D','A'])

D  C  B  A
11  1  1  2  1
21  1  8  8  7
13  2  2  8  1
44  2  9  3  2

## 순위(Ranking) 

### `pd.rank( )`

|메소드|설명|
|:---|:----|
|`average`|기본값. 순위에 같은 값을 가지는 항목들의 평균값을 사용|
|`min`|같은 값을 가지는 그룹을 낮은 순위로 지정|
|`max`|같은 값을 가지는 그룹을 높은 순위로 지정|
|`first`|데이터 내의 위치에 따라 순위 지정|
|`dense`|같은 그룹 내에서 모두 같은 순위를 적 용하지 않고 1씩 증가|


In [194]:
s = pd.Series([-5, -4, -3, 0, 1, 1, 4, 5, 6, 6, 7, 8, 9, 9 ])
s

0    -5
1    -4
2    -3
3     0
4     1
5     1
6     4
7     5
8     6
9     6
10    7
11    8
12    9
13    9
dtype: int64

`average`	기본값. 순위에 같은 값을 가지는 항목들의 평균값을 사용

In [195]:
s.rank() # defalut : method = average

0      1.0
1      2.0
2      3.0
3      4.0
4      5.5
5      5.5
6      7.0
7      8.0
8      9.5
9      9.5
10    11.0
11    12.0
12    13.5
13    13.5
dtype: float64

In [196]:
s.rank(method='min')

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      5.0
6      7.0
7      8.0
8      9.0
9      9.0
10    11.0
11    12.0
12    13.0
13    13.0
dtype: float64

In [197]:
s.rank(method='max')

0      1.0
1      2.0
2      3.0
3      4.0
4      6.0
5      6.0
6      7.0
7      8.0
8     10.0
9     10.0
10    11.0
11    12.0
12    14.0
13    14.0
dtype: float64

In [198]:
s.rank(method='first') # 먼저 적힌 것(index가 빠른것)이 순위를 높여준다.

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
12    13.0
13    14.0
dtype: float64

###  axis = 1

In [209]:
df = pd.DataFrame(np.random.randint(1, 4, (3, 3)))
df

0  1  2
0  2  3  1
1  2  1  3
2  2  3  2

In [210]:
df.rank(axis=1)

0    1    2
0  2.0  3.0  1.0
1  2.0  1.0  3.0
2  1.5  3.0  1.5

### groupby().rank() 그룹별 랭크 구하기

In [200]:
subject = ['Korean']*3 + ['DataSience']*3 + ['Python']*3
score = np.random.randint(40, 100, 9)
df = pd.DataFrame({'subject':subject, 'score':score})
df

subject  score
0      Korean     56
1      Korean     78
2      Korean     85
3  DataSience     66
4  DataSience     55
5  DataSience     79
6      Python     95
7      Python     42
8      Python     47

In [207]:
df['rank_by_score_per_course'] = df.groupby('subject').score.rank(ascending=False)
df.sort_values(by=['subject', 'rank_by_score_per_course'])

subject  score  rank_by_score_per_course
5  DataSience     79                       1.0
3  DataSience     66                       2.0
4  DataSience     55                       3.0
2      Korean     85                       1.0
1      Korean     78                       2.0
0      Korean     56                       3.0
6      Python     95                       1.0
8      Python     47                       2.0
7      Python     42                       3.0

## 고성능 연산 

In [175]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [176]:
%timeit df1 + df2 + df3 + df4

42.7 ms ± 710 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [177]:
%timeit pd.eval('df1 + df2 + df3 + df4')

21.2 ms ± 621 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [178]:
%timeit df1 * -df2 / (-df3 * df4)

80.7 ms ± 1.65 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [179]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

21.5 ms ± 567 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [180]:
%timeit (df1 < df2) & (df2 <= df3 ) & (df3 != df4)

31.2 ms ± 536 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [181]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3 ) & (df3 != df4)')

17.2 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [182]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=['A', 'B', 'C', 'D', 'E'])
df.head()

A         B         C         D         E
0  0.537540  0.791138  0.026901  0.295238  0.058951
1  0.331023  0.865987  0.356146  0.120927  0.344336
2  0.305984  0.415555  0.501481  0.427603  0.513875
3  0.241720  0.079683  0.107477  0.788019  0.652216
4  0.398776  0.823933  0.138966  0.038742  0.238497

In [183]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

9.03 ms ± 273 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [184]:
%timeit pd.eval(' df.A + df.B / df.C - df.D * df.E')


2.98 ms ± 50.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [185]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

A         B         C         D         E          R
0  0.537540  0.791138  0.026901  0.295238  0.058951  29.929784
1  0.331023  0.865987  0.356146  0.120927  0.344336   2.720935
2  0.305984  0.415555  0.501481  0.427603  0.513875   0.914905
3  0.241720  0.079683  0.107477  0.788019  0.652216   0.469157
4  0.398776  0.823933  0.138966  0.038742  0.238497   6.318578

In [186]:
col_mean = df.mean(1)
df['A'] + col_mean

0         5.810799
1         1.120916
2         0.819218
3         0.631433
4         1.725025
            ...   
999995    1.528414
999996    1.734957
999997    0.841553
999998    1.639869
999999    0.633138
Length: 1000000, dtype: float64

In [187]:
df.eval(' A + @col_mean')

0         5.810799
1         1.120916
2         0.819218
3         0.631433
4         1.725025
            ...   
999995    1.528414
999996    1.734957
999997    0.841553
999998    1.639869
999999    0.633138
Length: 1000000, dtype: float64

In [188]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

A         B         C         D         E         R
2       0.305984  0.415555  0.501481  0.427603  0.513875  0.914905
8       0.064225  0.344704  0.612615  0.587804  0.063718  0.589448
15      0.161247  0.334611  0.812951  0.632078  0.980505 -0.046907
18      0.101054  0.042466  0.560278  0.920727  0.467766 -0.253836
22      0.168396  0.010100  0.655068  0.509721  0.433047 -0.036918
...          ...       ...       ...       ...       ...       ...
999983  0.016915  0.283985  0.639740  0.539523  0.557632  0.159966
999985  0.097388  0.364369  0.735489  0.303723  0.058166  0.575132
999994  0.094129  0.307854  0.659409  0.610863  0.343870  0.350934
999997  0.343857  0.298998  0.968279  0.668548  0.162460  0.544038
999999  0.135227  0.427201  0.519139  0.878997  0.568363  0.458541

[125189 rows x 6 columns]

In [189]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]')

A         B         C         D         E         R
2       0.305984  0.415555  0.501481  0.427603  0.513875  0.914905
8       0.064225  0.344704  0.612615  0.587804  0.063718  0.589448
15      0.161247  0.334611  0.812951  0.632078  0.980505 -0.046907
18      0.101054  0.042466  0.560278  0.920727  0.467766 -0.253836
22      0.168396  0.010100  0.655068  0.509721  0.433047 -0.036918
...          ...       ...       ...       ...       ...       ...
999983  0.016915  0.283985  0.639740  0.539523  0.557632  0.159966
999985  0.097388  0.364369  0.735489  0.303723  0.058166  0.575132
999994  0.094129  0.307854  0.659409  0.610863  0.343870  0.350934
999997  0.343857  0.298998  0.968279  0.668548  0.162460  0.544038
999999  0.135227  0.427201  0.519139  0.878997  0.568363  0.458541

[125189 rows x 6 columns]

In [190]:
df.query('(A < 0.5) and (B < 0.5) and (C > 0.5)')

A         B         C         D         E         R
2       0.305984  0.415555  0.501481  0.427603  0.513875  0.914905
8       0.064225  0.344704  0.612615  0.587804  0.063718  0.589448
15      0.161247  0.334611  0.812951  0.632078  0.980505 -0.046907
18      0.101054  0.042466  0.560278  0.920727  0.467766 -0.253836
22      0.168396  0.010100  0.655068  0.509721  0.433047 -0.036918
...          ...       ...       ...       ...       ...       ...
999983  0.016915  0.283985  0.639740  0.539523  0.557632  0.159966
999985  0.097388  0.364369  0.735489  0.303723  0.058166  0.575132
999994  0.094129  0.307854  0.659409  0.610863  0.343870  0.350934
999997  0.343857  0.298998  0.968279  0.668548  0.162460  0.544038
999999  0.135227  0.427201  0.519139  0.878997  0.568363  0.458541

[125189 rows x 6 columns]

In [191]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

A         B         C         D         E         R
2       0.305984  0.415555  0.501481  0.427603  0.513875  0.914905
3       0.241720  0.079683  0.107477  0.788019  0.652216  0.469157
6       0.192825  0.186688  0.337018  0.620233  0.613244  0.366409
8       0.064225  0.344704  0.612615  0.587804  0.063718  0.589448
15      0.161247  0.334611  0.812951  0.632078  0.980505 -0.046907
...          ...       ...       ...       ...       ...       ...
999993  0.297915  0.195860  0.310892  0.090206  0.339968  0.897243
999994  0.094129  0.307854  0.659409  0.610863  0.343870  0.350934
999995  0.480763  0.240544  0.057884  0.385276  0.788992  4.332443
999997  0.343857  0.298998  0.968279  0.668548  0.162460  0.544038
999999  0.135227  0.427201  0.519139  0.878997  0.568363  0.458541

[250255 rows x 6 columns]

In [192]:
df.query(' A < @col_mean and B < @col_mean')

A         B         C         D         E         R
2       0.305984  0.415555  0.501481  0.427603  0.513875  0.914905
3       0.241720  0.079683  0.107477  0.788019  0.652216  0.469157
6       0.192825  0.186688  0.337018  0.620233  0.613244  0.366409
8       0.064225  0.344704  0.612615  0.587804  0.063718  0.589448
15      0.161247  0.334611  0.812951  0.632078  0.980505 -0.046907
...          ...       ...       ...       ...       ...       ...
999993  0.297915  0.195860  0.310892  0.090206  0.339968  0.897243
999994  0.094129  0.307854  0.659409  0.610863  0.343870  0.350934
999995  0.480763  0.240544  0.057884  0.385276  0.788992  4.332443
999997  0.343857  0.298998  0.968279  0.668548  0.162460  0.544038
999999  0.135227  0.427201  0.519139  0.878997  0.568363  0.458541

[250255 rows x 6 columns]

출처: 
* <a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


<br>


* [이수안컴퓨터연구소](https://www.youtube.com/channel/UCFfALXX0DOx7zv6VeR5U_Bg)
* https://github.com/minsuk-heo/pandas