<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>



In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.3'

# 데이터 연산

## 연산자 범용 함수

|||
|----|----|
|`add()` |덧셈 (+)|
|`sub()` | 뺄셈 (-)|
|`mul()` | 곱셈(\*)|
|`div()` | 몫 (/)|
|`mod()` | 나머지(//)|
|`pow()` | 지수 (\*\*)|



https://kongdols-room.tistory.com/126

### add()

In [2]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[5, 5, 6],
       [9, 2, 2],
       [5, 4, 4]])

In [3]:
a + a[0]

array([[10, 10, 12],
       [14,  7,  8],
       [10,  9, 10]])

In [4]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  5  5  6
1  9  2  2
2  5  4  4

In [5]:
df + df.iloc[0]

A   B   C
0  10  10  12
1  14   7   8
2  10   9  10

In [6]:
df.add(df.iloc[0])

A   B   C
0  10  10  12
1  14   7   8
2  10   9  10

###  `sub()`

In [7]:
a - a[0]

array([[ 0,  0,  0],
       [ 4, -3, -4],
       [ 0, -1, -2]])

In [8]:
df

A  B  C
0  5  5  6
1  9  2  2
2  5  4  4

In [9]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  4 -3 -4
2  0 -1 -2

###### 컬럼 단위로 빼주기 위해서는~

`sub(axis=0) ` 을 사용해 준다. 

In [10]:
df.iloc[:, 0]

0    5
1    9
2    5
Name: A, dtype: int32

결과 값이 원하는대로 나오지 않는다. 

In [11]:
df - df.iloc[:, 0]

A   B   C   0   1   2
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN

axis=0 

In [12]:
df.sub(df.iloc[:,0], axis=0)

A  B  C
0  0  0  1
1  0 -7 -7
2  0 -1 -1

### mul()

상식-0-
* 축약
    - mul : multiply
    - mat : matrix 

In [13]:
a

array([[5, 5, 6],
       [9, 2, 2],
       [5, 4, 4]])

In [14]:
a[1]

array([9, 2, 2])

In [15]:
a * a[1]

array([[45, 10, 12],
       [81,  4,  4],
       [45,  8,  8]])

In [16]:
df * df.iloc[1]

A   B   C
0  45  10  12
1  81   4   4
2  45   8   8

axis=0

In [17]:
df.mul(df.A, axis=0)

A   B   C
0  25  25  30
1  81  18  18
2  25  20  20

###  div()

* div() / divide()
* truediv()
* floordiv() : 정수 환원

In [18]:
a

array([[5, 5, 6],
       [9, 2, 2],
       [5, 4, 4]])

In [19]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [1.8       , 0.4       , 0.33333333],
       [1.        , 0.8       , 0.66666667]])

In [20]:
a / 0

<ipython-input-20-4f74cdd1c1e6>:1: RuntimeWarning: divide by zero encountered in true_divide
  a / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [21]:
df

A  B  C
0  5  5  6
1  9  2  2
2  5  4  4

In [22]:
df / df.iloc[0]

A    B         C
0  1.0  1.0  1.000000
1  1.8  0.4  0.333333
2  1.0  0.8  0.666667

In [23]:
df.div(df['A'],axis=0)

A         B         C
0  1.0  1.000000  1.200000
1  1.0  0.222222  0.222222
2  1.0  0.800000  0.800000

In [24]:
df.truediv(df['A'],axis=0)

A         B         C
0  1.0  1.000000  1.200000
1  1.0  0.222222  0.222222
2  1.0  0.800000  0.800000

In [25]:
df.floordiv(df['A'],axis=0)

A  B  C
0  1  1  1
1  1  0  0
2  1  0  0

### mod()

In [26]:
a

array([[5, 5, 6],
       [9, 2, 2],
       [5, 4, 4]])

In [27]:
a % a[0]

array([[0, 0, 0],
       [4, 2, 2],
       [0, 4, 4]], dtype=int32)

In [28]:
df

A  B  C
0  5  5  6
1  9  2  2
2  5  4  4

In [29]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  4  2  2
2  0  4  4

In [30]:
df.mod(df.iloc[:,0], axis=0)

A  B  C
0  0  0  1
1  0  2  2
2  0  4  4

### pow()

In [31]:
a

array([[5, 5, 6],
       [9, 2, 2],
       [5, 4, 4]])

In [32]:
a ** a[0]

array([[ 3125,  3125, 46656],
       [59049,    32,    64],
       [ 3125,  1024,  4096]], dtype=int32)

In [33]:
df.pow(df.iloc[0])

A     B      C
0   3125  3125  46656
1  59049    32     64
2   3125  1024   4096

In [34]:
df.pow(df.iloc[:,0], axis=0)

A     B     C
0       3125  3125  7776
1  387420489   512   512
2       3125  1024  1024

In [35]:
row = df.iloc[0, ::2]
row


A    5
C    6
Name: 0, dtype: int32

In [36]:
df

A  B  C
0  5  5  6
1  9  2  2
2  5  4  4

In [37]:
df - row

A   B    C
0  0.0 NaN  0.0
1  4.0 NaN -4.0
2  0.0 NaN -2.0

## 정렬(Sorting)

1. sort_index() : axis= 0 , axis=1
2. sort_values() : by=['A'], by=['A','C']
3. head(), tail()
4. nlargest(), nsmallest() : n = int , col

In [38]:
s = pd.Series(range(5), index=['A', 'D', 'B', 'C', 'E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [39]:
s= s.sort_index()
s

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [40]:
df = pd.DataFrame(np.random.randint(1, 10, (4,4)),
                  columns=list('BDAC'),
                  index=[21, 11, 13, 44])
df

B  D  A  C
21  2  5  9  4
11  2  4  3  2
13  4  1  3  8
44  9  8  9  2

### sort_index()

In [41]:
df.sort_index()# default axis=0

B  D  A  C
11  2  4  3  2
13  4  1  3  8
21  2  5  9  4
44  9  8  9  2

컬럼이름으로 정렬하기 

In [42]:
df.sort_index(axis=1)

A  B  C  D
21  9  2  4  5
11  3  2  2  4
13  3  4  8  1
44  9  9  2  8

### sort_values()

In [43]:
s

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [44]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [45]:
df

B  D  A  C
21  2  5  9  4
11  2  4  3  2
13  4  1  3  8
44  9  8  9  2

In [46]:
df.iloc[:,1] = [1, 1, 2, 2]
df

B  D  A  C
21  2  1  9  4
11  2  1  3  2
13  4  2  3  8
44  9  2  9  2

In [47]:
df.sort_values(by=['D'])

B  D  A  C
21  2  1  9  4
11  2  1  3  2
13  4  2  3  8
44  9  2  9  2

In [48]:
df.sort_values(by=['D','A'])

B  D  A  C
11  2  1  3  2
21  2  1  9  4
13  4  2  3  8
44  9  2  9  2

In [49]:
df.sort_index(axis=1, ascending=False).sort_values(by=['D','A'])

D  C  B  A
11  1  2  2  3
21  1  4  2  9
13  2  8  4  3
44  2  2  9  9

### `head()`, `tail()`

In [50]:
df = pd.DataFrame([[1, 1, 1, 1],[2, 2, 2,2],[2, 2, 2, 2], [3, 3, 3, 4], [4, 4, 5, 5]], columns=list('ABCD'))
df

A  B  C  D
0  1  1  1  1
1  2  2  2  2
2  2  2  2  2
3  3  3  3  4
4  4  4  5  5

In [51]:
df.head(3)

A  B  C  D
0  1  1  1  1
1  2  2  2  2
2  2  2  2  2

In [52]:
df.tail(3)

A  B  C  D
2  2  2  2  2
3  3  3  3  4
4  4  4  5  5

### `nlargest()`, `nsmallest()`

* `nlargest(n, columns=)`
* `nsmallest(n, columns=)`
* keep= 'first', 'last', 'all' : 동순위 처리 기준

In [53]:
df.nlargest(3, columns='A')

A  B  C  D
4  4  4  5  5
3  3  3  3  4
1  2  2  2  2

In [54]:
df.nsmallest(2, columns='C')

A  B  C  D
0  1  1  1  1
1  2  2  2  2

In [55]:
df.nsmallest(3, columns='D')

A  B  C  D
0  1  1  1  1
1  2  2  2  2
2  2  2  2  2

In [56]:
df.nsmallest(2, columns='A', keep='last')

A  B  C  D
0  1  1  1  1
2  2  2  2  2

In [57]:
df.nsmallest(2, columns='A', keep='first')

A  B  C  D
0  1  1  1  1
1  2  2  2  2

In [58]:
df.nsmallest(2, columns='A', keep='all')

A  B  C  D
0  1  1  1  1
1  2  2  2  2
2  2  2  2  2

## 순위(Ranking) 

### `pd.rank( )`

|메소드|설명|
|:---|:----|
|`average`|기본값. 순위에 같은 값을 가지는 항목들의 평균값을 사용|
|`min`|같은 값을 가지는 그룹을 낮은 순위로 지정|
|`max`|같은 값을 가지는 그룹을 높은 순위로 지정|
|`first`|데이터 내의 위치에 따라 순위 지정|
|`dense`|같은 그룹 내에서 모두 같은 순위를 적 용하지 않고 1씩 증가|


In [59]:
s = pd.Series([-5, -4, -3, 0, 1, 1, 4, 5, 6, 6, 7, 8, 9, 9 ])
s

0    -5
1    -4
2    -3
3     0
4     1
5     1
6     4
7     5
8     6
9     6
10    7
11    8
12    9
13    9
dtype: int64

`average`	기본값. 순위에 같은 값을 가지는 항목들의 평균값을 사용

In [60]:
s.rank() # defalut : method = average

0      1.0
1      2.0
2      3.0
3      4.0
4      5.5
5      5.5
6      7.0
7      8.0
8      9.5
9      9.5
10    11.0
11    12.0
12    13.5
13    13.5
dtype: float64

In [61]:
s.rank(method='min')

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      5.0
6      7.0
7      8.0
8      9.0
9      9.0
10    11.0
11    12.0
12    13.0
13    13.0
dtype: float64

In [62]:
s.rank(method='max')

0      1.0
1      2.0
2      3.0
3      4.0
4      6.0
5      6.0
6      7.0
7      8.0
8     10.0
9     10.0
10    11.0
11    12.0
12    14.0
13    14.0
dtype: float64

In [63]:
s.rank(method='first') # 먼저 적힌 것(index가 빠른것)이 순위를 높여준다.

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
12    13.0
13    14.0
dtype: float64

###  axis = 1

In [64]:
df = pd.DataFrame(np.random.randint(1, 4, (3, 3)))
df

0  1  2
0  2  1  3
1  1  3  2
2  1  1  1

In [65]:
df.rank(axis=1)

0    1    2
0  2.0  1.0  3.0
1  1.0  3.0  2.0
2  2.0  2.0  2.0

### groupby().rank() 그룹별 랭크 구하기

In [66]:
subject = ['Korean']*3 + ['DataSience']*3 + ['Python']*3
score = np.random.randint(40, 100, 9)
df = pd.DataFrame({'subject':subject, 'score':score})
df

subject  score
0      Korean     93
1      Korean     88
2      Korean     61
3  DataSience     56
4  DataSience     74
5  DataSience     89
6      Python     42
7      Python     62
8      Python     65

In [67]:
df['rank_by_score_per_course'] = df.groupby('subject').score.rank(ascending=False)
df.sort_values(by=['subject', 'rank_by_score_per_course'])

subject  score  rank_by_score_per_course
5  DataSience     89                       1.0
4  DataSience     74                       2.0
3  DataSience     56                       3.0
0      Korean     93                       1.0
1      Korean     88                       2.0
2      Korean     61                       3.0
8      Python     65                       1.0
7      Python     62                       2.0
6      Python     42                       3.0

## 고성능 연산 

In [68]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [69]:
%timeit df1 + df2 + df3 + df4

153 ms ± 7.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [70]:
%timeit pd.eval('df1 + df2 + df3 + df4')

60 ms ± 663 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [71]:
%timeit df1 * -df2 / (-df3 * df4)

226 ms ± 1.17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [72]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

62.7 ms ± 1.68 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [73]:
%timeit (df1 < df2) & (df2 <= df3 ) & (df3 != df4)

77.9 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [74]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3 ) & (df3 != df4)')

32.6 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [75]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=['A', 'B', 'C', 'D', 'E'])
df.head()

A         B         C         D         E
0  0.929796  0.374975  0.842295  0.168242  0.495083
1  0.767693  0.755878  0.667809  0.464528  0.825742
2  0.357488  0.513910  0.612768  0.217818  0.292276
3  0.243509  0.340379  0.958095  0.111965  0.860189
4  0.698364  0.791494  0.689426  0.147807  0.885246

In [76]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

26.2 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [77]:
%timeit pd.eval(' df.A + df.B / df.C - df.D * df.E')


8.02 ms ± 74 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [78]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.929796  0.374975  0.842295  0.168242  0.495083  1.291685
1  0.767693  0.755878  0.667809  0.464528  0.825742  1.515990
2  0.357488  0.513910  0.612768  0.217818  0.292276  1.132495
3  0.243509  0.340379  0.958095  0.111965  0.860189  0.502464
4  0.698364  0.791494  0.689426  0.147807  0.885246  1.715567

In [79]:
col_mean = df.mean(1)
df['A'] + col_mean

0         1.613475
1         1.600634
2         0.878614
3         0.746276
4         1.519681
            ...   
999995    1.176396
999996    1.153329
999997    1.477540
999998    1.515211
999999    1.876218
Length: 1000000, dtype: float64

In [80]:
df.eval(' A + @col_mean')

0         1.613475
1         1.600634
2         0.878614
3         0.746276
4         1.519681
            ...   
999995    1.176396
999996    1.153329
999997    1.477540
999998    1.515211
999999    1.876218
Length: 1000000, dtype: float64

In [81]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

A         B         C         D         E         R
3       0.243509  0.340379  0.958095  0.111965  0.860189  0.502464
15      0.184811  0.315975  0.599823  0.260280  0.143633  0.674207
18      0.168428  0.202726  0.678752  0.760399  0.087487  0.400578
49      0.483196  0.004886  0.897510  0.311090  0.140035  0.445077
63      0.489483  0.061027  0.533127  0.956603  0.283647  0.332614
...          ...       ...       ...       ...       ...       ...
999947  0.326080  0.427107  0.802618  0.721614  0.401218  0.568698
999949  0.275328  0.020602  0.912136  0.270016  0.193818  0.245580
999974  0.229350  0.476948  0.913190  0.164629  0.539087  0.662888
999975  0.109146  0.079963  0.935200  0.621483  0.816653 -0.312886
999983  0.043200  0.047134  0.764075  0.627390  0.239410 -0.045316

[124713 rows x 6 columns]

In [82]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]')

A         B         C         D         E         R
3       0.243509  0.340379  0.958095  0.111965  0.860189  0.502464
15      0.184811  0.315975  0.599823  0.260280  0.143633  0.674207
18      0.168428  0.202726  0.678752  0.760399  0.087487  0.400578
49      0.483196  0.004886  0.897510  0.311090  0.140035  0.445077
63      0.489483  0.061027  0.533127  0.956603  0.283647  0.332614
...          ...       ...       ...       ...       ...       ...
999947  0.326080  0.427107  0.802618  0.721614  0.401218  0.568698
999949  0.275328  0.020602  0.912136  0.270016  0.193818  0.245580
999974  0.229350  0.476948  0.913190  0.164629  0.539087  0.662888
999975  0.109146  0.079963  0.935200  0.621483  0.816653 -0.312886
999983  0.043200  0.047134  0.764075  0.627390  0.239410 -0.045316

[124713 rows x 6 columns]

In [83]:
df.query('(A < 0.5) and (B < 0.5) and (C > 0.5)')

A         B         C         D         E         R
3       0.243509  0.340379  0.958095  0.111965  0.860189  0.502464
15      0.184811  0.315975  0.599823  0.260280  0.143633  0.674207
18      0.168428  0.202726  0.678752  0.760399  0.087487  0.400578
49      0.483196  0.004886  0.897510  0.311090  0.140035  0.445077
63      0.489483  0.061027  0.533127  0.956603  0.283647  0.332614
...          ...       ...       ...       ...       ...       ...
999947  0.326080  0.427107  0.802618  0.721614  0.401218  0.568698
999949  0.275328  0.020602  0.912136  0.270016  0.193818  0.245580
999974  0.229350  0.476948  0.913190  0.164629  0.539087  0.662888
999975  0.109146  0.079963  0.935200  0.621483  0.816653 -0.312886
999983  0.043200  0.047134  0.764075  0.627390  0.239410 -0.045316

[124713 rows x 6 columns]

In [84]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

A         B         C         D         E         R
3       0.243509  0.340379  0.958095  0.111965  0.860189  0.502464
15      0.184811  0.315975  0.599823  0.260280  0.143633  0.674207
18      0.168428  0.202726  0.678752  0.760399  0.087487  0.400578
21      0.375727  0.418956  0.473027  0.774259  0.556852  0.830271
23      0.044325  0.187811  0.348110  0.333748  0.225103  0.508714
...          ...       ...       ...       ...       ...       ...
999963  0.147827  0.306217  0.154446  0.297354  0.122870  2.093968
999974  0.229350  0.476948  0.913190  0.164629  0.539087  0.662888
999975  0.109146  0.079963  0.935200  0.621483  0.816653 -0.312886
999983  0.043200  0.047134  0.764075  0.627390  0.239410 -0.045316
999987  0.240405  0.390846  0.335919  0.365985  0.700493  1.147547

[249939 rows x 6 columns]

In [85]:
df.query(' A < @col_mean and B < @col_mean')

A         B         C         D         E         R
3       0.243509  0.340379  0.958095  0.111965  0.860189  0.502464
15      0.184811  0.315975  0.599823  0.260280  0.143633  0.674207
18      0.168428  0.202726  0.678752  0.760399  0.087487  0.400578
21      0.375727  0.418956  0.473027  0.774259  0.556852  0.830271
23      0.044325  0.187811  0.348110  0.333748  0.225103  0.508714
...          ...       ...       ...       ...       ...       ...
999963  0.147827  0.306217  0.154446  0.297354  0.122870  2.093968
999974  0.229350  0.476948  0.913190  0.164629  0.539087  0.662888
999975  0.109146  0.079963  0.935200  0.621483  0.816653 -0.312886
999983  0.043200  0.047134  0.764075  0.627390  0.239410 -0.045316
999987  0.240405  0.390846  0.335919  0.365985  0.700493  1.147547

[249939 rows x 6 columns]

출처: 
* <a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


<br>


* [이수안컴퓨터연구소](https://www.youtube.com/channel/UCFfALXX0DOx7zv6VeR5U_Bg)
* https://github.com/minsuk-heo/pandas