<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


In [21]:
import numpy as np
np.__version__

'1.19.2'

# 비교 연산(Comparison Operators)


## All & Any

- Array 의 데이터 전부(and) 또는 일부(or)  가 조건에 만족 여부 반환

any : 하나라도 조건에 만족한다면 true

all : 모두가 조건에 만족한다면 true

In [22]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.any(a>5), np.any(a<0)

(True, False)

In [24]:
np.all(a>5), np.all(a<10)

(False, True)

## 비교 범용 함수

|연산자|비교 범용 함수|
|:-|:-|
|`==`|`np.equal`|
|`!=`|`np.not_equal`|
|`<`|`пр.less`|
|`<=`|`np.less_equal`|
|`>`|`np.greater`|
|`>=`|`np.greater_equal`|








In [25]:
a1 = np.arange(1, 10)
print(a1)

print(a1 == 5)
print(a1 != 3)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True False  True  True  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [26]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any(a2 > 5))
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))
print(np.all(a2 > 5))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


|비교 범용 함수|설명|
|:--|:-|
|`np.isclose`|배열 두개가 (z\*1e+02)% 내외로 가까우면 True, 아니면 False|
|`np.isinf`|배열이 inf이면 True, 아니면 False|
|`np.isfinite`|배열이 inf, nan이면 False, 아니면 True|
|`np.isnan`|배열이 nan이면 True, 아니면 False|

In [27]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1))


[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [28]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


## 불리언 연산자(Boolean Operators)


|연산자|비교 범용 함수|
|:-:|:-|
|`&`|`np.bitwise_and`|
|`\|`|`np.bitwise_or`|
|`^`|`np.bitwise_xor`|
|`~`|`np.bitwise_not`|







In [29]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)]) # 불리언 인덱싱

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5) )
print(a2[~(a2 > 5)])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


## where, isnan, isfinite

### np.where()

`np.where(condition, True, False)`

In [30]:
a = np.array([1, 2, 3, 4,4, 5, 1, 7, 8,9])
np.where(a > 4)

(array([5, 7, 8, 9], dtype=int64),)

In [31]:
a = np.array([1, 2, 3, 4, 5])

np.where(a> 3, 0, 1)

array([1, 1, 1, 0, 0])

### np.isnan()

In [32]:
a = np.array([1, np.NaN, np.inf], float)
np.isnan(a)

array([False,  True, False])

### np.isfinite()

In [33]:
a = np.array([1, np.NaN, np.inf], float)
np.isfinite(a)

array([ True, False, False])

In [34]:
np.isfortran(a)

False

출처:

* <a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


<br>

* [TeamLab](https://www.youtube.com/watch?v=aHthqCgsSFs&list=PLBHVuYlKEkULZLnKLzRq1CnNBOBlBTkqp)

* [이수안컴퓨터연구소](https://www.youtube.com/watch?v=mirZPrWwvao&list=PL7ZVZgsnLwEEZcVusN-fV_sJhQHq833OS&index=1)