<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


In [1]:
import numpy as np
np.__version__

'1.19.2'

# 비교 연산(Comparison Operators)


## All & Any

- Array 의 데이터 전부(and) 또는 일부(or)  가 조건에 만족 여부 반환

any : 하나라도 조건에 만족한다면 true

all : 모두가 조건에 만족한다면 true

In [2]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
np.any(a>5), np.any(a<0)

(True, False)

In [4]:
np.all(a>5), np.all(a<10)

(False, True)

## 비교 범용 함수

|연산자|비교 범용 함수|
|:-|:-|
|`==`|`np.equal`|
|`!=`|`np.not_equal`|
|`<`|`пр.less`|
|`<=`|`np.less_equal`|
|`>`|`np.greater`|
|`>=`|`np.greater_equal`|








In [5]:
a1 = np.arange(1, 10)
print(a1)

print(a1 == 5)
print(a1 != 3)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True False  True  True  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [6]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any(a2 > 5))
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))
print(np.all(a2 > 5))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


|비교 범용 함수|설명|
|:--|:-|
|`np.isclose`|배열 두개가 (z\*1e+02)% 내외로 가까우면 True, 아니면 False|
|`np.isinf`|배열이 inf이면 True, 아니면 False|
|`np.isfinite`|배열이 inf, nan이면 False, 아니면 True|
|`np.isnan`|배열이 nan이면 True, 아니면 False|

In [7]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1))


[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [8]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


## 불리언 연산자(Boolean Operators)


|연산자|비교 범용 함수|
|:-:|:-|
|`&`|`np.bitwise_and`|
|`\|`|`np.bitwise_or`|
|`^`|`np.bitwise_xor`|
|`~`|`np.bitwise_not`|







In [9]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)]) # 불리언 인덱싱

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5) )
print(a2[~(a2 > 5)])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


## where, isnan, isfinite

### `np.where()`

`np.where(condition, True, False)`

In [10]:
a = np.array([1, 2, 3, 4,4, 5, 1, 7, 8,9])
np.where(a > 4)

(array([5, 7, 8, 9], dtype=int64),)

In [11]:
a = np.array([1, 2, 3, 4, 5])

np.where(a> 3, 0, 1)

array([1, 1, 1, 0, 0])

#### 조회 

In [12]:
import numpy as np

In [13]:
array = np.random.choice(np.arange(50),16).reshape(4,-1)
array

array([[17, 11, 42, 28],
       [19, 13,  1,  5],
       [42, 44, 32,  4],
       [47, 35,  7, 24]])

In [14]:
np.where(array>25)

(array([0, 0, 2, 2, 2, 3, 3], dtype=int64),
 array([2, 3, 0, 1, 2, 0, 1], dtype=int64))

In [15]:
array[np.where(array>25)]

array([42, 28, 42, 44, 32, 47, 35])

#### 값변경

In [16]:
array = np.random.choice(np.arange(50),16).reshape(4,-1)
array

array([[ 4, 12, 44, 45],
       [47, 11, 19, 42],
       [34, 24,  4, 24],
       [12, 19, 38, 35]])

In [17]:
array[np.where(array>25)]= 100
array

array([[  4,  12, 100, 100],
       [100,  11,  19, 100],
       [100,  24,   4,  24],
       [ 12,  19, 100, 100]])

### `np.isnan()`

In [18]:
a = np.array([1, np.NaN, np.inf], float)
np.isnan(a)

array([False,  True, False])

### `np.isfinite()`

In [19]:
a = np.array([1, np.NaN, np.inf], float)
np.isfinite(a)

array([ True, False, False])

In [20]:
np.isfortran(a)

False

출처:

* <a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


<br>

* [TeamLab](https://www.youtube.com/watch?v=aHthqCgsSFs&list=PLBHVuYlKEkULZLnKLzRq1CnNBOBlBTkqp)

* [이수안컴퓨터연구소](https://www.youtube.com/watch?v=mirZPrWwvao&list=PL7ZVZgsnLwEEZcVusN-fV_sJhQHq833OS&index=1)