<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>

In [2]:
import numpy as np
np.__version__

'1.19.2'

### 배열 정렬

In [3]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1))
print('----------')
print(a1)
print(np.argsort(a1))
print('----------')
print(a1)
a1.sort()
print(a1)

[1 6 1 8 8 1 6 2 9 7]
[1 1 1 2 6 6 7 8 8 9]
----------
[1 6 1 8 8 1 6 2 9 7]
[0 2 5 7 1 6 9 3 4 8]
----------
[1 6 1 8 8 1 6 2 9 7]
[1 1 1 2 6 6 7 8 8 9]


In [6]:
print(a1)
print(np.sort(a1))
print('----------')
a1_argsort = np.argsort(a1)
print(a1_argsort)
print(a1[a1_argsort])

[1 1 1 2 6 6 7 8 8 9]
[1 1 1 2 6 6 7 8 8 9]
----------
[0 1 2 3 4 5 6 7 8 9]
[1 1 1 2 6 6 7 8 8 9]


In [8]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[5 7 7]
 [1 5 8]
 [9 9 1]]
[[1 5 1]
 [5 7 7]
 [9 9 8]]
[[5 7 7]
 [1 5 8]
 [1 9 9]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [9]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3))

[5 1 7 9 4 7 1 3 4 8]
[1 1 3 4 4 5 7 9 7 8]


In [10]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))


[[8 3 5 3 1]
 [6 1 2 7 7]
 [8 9 1 1 4]
 [5 2 2 7 1]
 [1 2 7 8 7]]
[[3 1 3 5 8]
 [1 2 6 7 7]
 [1 1 4 8 9]
 [1 2 2 5 7]
 [2 1 7 7 8]]
[[5 2 2 1 1]
 [1 2 1 3 1]
 [6 1 2 7 4]
 [8 3 5 7 7]
 [8 9 7 8 7]]
[[3 1 3 5 8]
 [1 2 6 7 7]
 [1 1 4 8 9]
 [1 2 2 5 7]
 [2 1 7 7 8]]


출처:

* <a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


<br>

* [TeamLab](https://www.youtube.com/watch?v=aHthqCgsSFs&list=PLBHVuYlKEkULZLnKLzRq1CnNBOBlBTkqp)

* [이수안컴퓨터연구소](https://www.youtube.com/watch?v=mirZPrWwvao&list=PL7ZVZgsnLwEEZcVusN-fV_sJhQHq833OS&index=1)