<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>

In [1]:
import numpy as np
np.__version__

'1.20.2'

# Sort
|code|설명|
|:-|:-|
|`ndarray.sort()`|In-place sort|
|`np.sort`|Return a sorted copy of an array|
|`np.argsort`|Indirect sort|
|`np.lexsort`|Indirect stable sort with multiple keys|
|`np.argpartition`|Indirect partial sort|

`kind = ` 파라미터로 지정 할수 있다. 
```
=========== ======= ============= ============ ========
   kind      speed   worst case    work space   stable
=========== ======= ============= ============ ========
'quicksort'    1     O(n^2)            0          no
'heapsort'     3     O(n*log(n))       0          no
'mergesort'    2     O(n*log(n))      ~n/2        yes
'timsort'      2     O(n*log(n))      ~n/2        yes
=========== ======= ============= ============ ========
```

In [2]:
a1 = np.random.randint(1, 10, size=10)
a1

array([9, 1, 6, 3, 8, 4, 2, 2, 6, 2])

In [4]:
a2 = np.random.randint(1, 10, size=(5, 3))
a2

array([[3, 2, 2],
       [2, 7, 4],
       [9, 8, 4],
       [2, 4, 1],
       [6, 2, 5]])

In [22]:
a3 = np.random.randint(1, 30, size=(3, 3, 3))
a3

array([[[15, 24, 18],
        [ 7, 14,  7],
        [14, 27, 13]],

       [[19, 14, 21],
        [ 5, 14, 11],
        [22, 19, 21]],

       [[23, 28, 11],
        [ 8, 18,  2],
        [18, 25, 25]]])

## `array.sort()`

In [53]:
array = np.array([3, 4, 2, 1, 2, 4, 5])
array.sort()
array

array([1, 2, 2, 3, 4, 4, 5])

## `np.sort()`

In [5]:
np.sort(a1)

array([1, 2, 2, 2, 3, 4, 6, 6, 8, 9])

In [13]:
np.sort(a2)

array([[2, 2, 3],
       [2, 4, 7],
       [4, 8, 9],
       [1, 2, 4],
       [2, 5, 6]])

In [14]:
np.sort(a2, axis=0)

array([[2, 2, 1],
       [2, 2, 2],
       [3, 4, 4],
       [6, 7, 4],
       [9, 8, 5]])

In [23]:
a3

array([[[15, 24, 18],
        [ 7, 14,  7],
        [14, 27, 13]],

       [[19, 14, 21],
        [ 5, 14, 11],
        [22, 19, 21]],

       [[23, 28, 11],
        [ 8, 18,  2],
        [18, 25, 25]]])

In [26]:
np.sort(a3, axis=-1) # default, axis=2

array([[[15, 18, 24],
        [ 7,  7, 14],
        [13, 14, 27]],

       [[14, 19, 21],
        [ 5, 11, 14],
        [19, 21, 22]],

       [[11, 23, 28],
        [ 2,  8, 18],
        [18, 25, 25]]])

In [25]:
np.sort(a3, axis=1)

array([[[ 7, 14,  7],
        [14, 24, 13],
        [15, 27, 18]],

       [[ 5, 14, 11],
        [19, 14, 21],
        [22, 19, 21]],

       [[ 8, 18,  2],
        [18, 25, 11],
        [23, 28, 25]]])

In [24]:
np.sort(a3, axis=0)

array([[[15, 14, 11],
        [ 5, 14,  2],
        [14, 19, 13]],

       [[19, 24, 18],
        [ 7, 14,  7],
        [18, 25, 21]],

       [[23, 28, 21],
        [ 8, 18, 11],
        [22, 27, 25]]])

## `np.argsort()`

In [6]:
np.argsort(a1)

array([1, 6, 7, 9, 3, 5, 2, 8, 4, 0], dtype=int64)

In [7]:
a1[np.argsort(a1)]

array([1, 2, 2, 2, 3, 4, 6, 6, 8, 9])

In [30]:
a2

array([[3, 2, 2],
       [2, 7, 4],
       [9, 8, 4],
       [2, 4, 1],
       [6, 2, 5]])

In [49]:
idx = np.argsort(a2)
idx

array([[1, 2, 0],
       [0, 2, 1],
       [2, 1, 0],
       [2, 0, 1],
       [1, 2, 0]], dtype=int64)

In [51]:
np.take_along_axis(a2, idx, axis=-1)

array([[2, 2, 3],
       [2, 4, 7],
       [4, 8, 9],
       [1, 2, 4],
       [2, 5, 6]])

## `np.lexsort()`

활용 예1

In [58]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

In [59]:
[surnames[i] + ", " + first_names[i] for i in ind]

['Galilei, Galileo', 'Hertz, Gustav', 'Hertz, Heinrich']

활용 예2

In [63]:
a = ['A','B','C','A','B','C']
b = [1 , 2, 3, 4, 5, 6]
idx = np.lexsort((b, a)) # Sort by a first, then by a

In [98]:
ab = [(a[i],b[i]) for i in idx]
ab

[('A', 1), ('A', 4), ('B', 2), ('B', 5), ('C', 3), ('C', 6)]

`argsort` vs `lexsort`

In [99]:
np.random.shuffle(ab)
ab

[('B', 2), ('C', 3), ('C', 6), ('A', 4), ('B', 5), ('A', 1)]

In [100]:
ab = np.array(ab, dtype=np.dtype([('x','object'),('y',int)]))
ab

array([('B', 2), ('C', 3), ('C', 6), ('A', 4), ('B', 5), ('A', 1)],
      dtype=[('x', 'O'), ('y', '<i4')])

In [102]:
idx = np.argsort(ab)
idx

array([5, 3, 0, 4, 1, 2], dtype=int64)

In [103]:
ab[idx]

array([('A', 1), ('A', 4), ('B', 2), ('B', 5), ('C', 3), ('C', 6)],
      dtype=[('x', 'O'), ('y', '<i4')])

묶여 있다면 lexically 되어 있다면?! argsort도 같은 원리로 움직인다. 첫번째거 정렬하고 뒤에꺼 정렬!

In [80]:
x = np.array([(1,9), (5,4), (1,0), (4,4), (3,0), (4,2), (4,1)],
          dtype=np.dtype([('x', int), ('y', int)]))
x

array([(1, 9), (5, 4), (1, 0), (4, 4), (3, 0), (4, 2), (4, 1)],
      dtype=[('x', '<i4'), ('y', '<i4')])

# 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환
* `argpartition()` : 배열에서 k개의 작은 값을 반환하는 인덱스

## `np.partition()`

In [9]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3))

[5 1 7 9 4 7 1 3 4 8]
[1 1 3 4 4 5 7 9 7 8]


In [10]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))


[[8 3 5 3 1]
 [6 1 2 7 7]
 [8 9 1 1 4]
 [5 2 2 7 1]
 [1 2 7 8 7]]
[[3 1 3 5 8]
 [1 2 6 7 7]
 [1 1 4 8 9]
 [1 2 2 5 7]
 [2 1 7 7 8]]
[[5 2 2 1 1]
 [1 2 1 3 1]
 [6 1 2 7 4]
 [8 3 5 7 7]
 [8 9 7 8 7]]
[[3 1 3 5 8]
 [1 2 6 7 7]
 [1 1 4 8 9]
 [1 2 2 5 7]
 [2 1 7 7 8]]


## `np.argpartition()`

k개의 작은 원소를 앞으로 가져오는 인덱스를 환원한다. 

In [104]:
np.argpartition(a1,1)

array([1, 6, 2, 3, 4, 5, 0, 7, 8, 9], dtype=int64)

In [122]:
a1 = np.array([9, 3, 2, 1, 1, 2, 3, 4, 5])
np.random.shuffle(a1)
a1

array([5, 1, 9, 2, 3, 2, 1, 4, 3])

In [123]:
for i in range(9):
    print(i, a1[np.argpartition(a1, i)])

0 [1 5 9 2 3 2 1 4 3]
1 [1 1 9 2 3 2 5 4 3]
2 [1 1 2 9 3 2 5 4 3]
3 [1 1 2 2 3 3 9 4 5]
4 [1 1 2 2 3 3 9 4 5]
5 [2 3 1 2 1 3 9 4 5]
6 [2 3 1 2 1 3 4 5 9]
7 [2 3 1 2 1 3 4 5 9]
8 [2 3 1 2 1 3 4 5 9]


출처:

* <a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


<br>

* [TeamLab](https://www.youtube.com/watch?v=aHthqCgsSFs&list=PLBHVuYlKEkULZLnKLzRq1CnNBOBlBTkqp)

* [이수안컴퓨터연구소](https://www.youtube.com/watch?v=mirZPrWwvao&list=PL7ZVZgsnLwEEZcVusN-fV_sJhQHq833OS&index=1)