<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>

In [16]:
import numpy as np
np.__version__

'1.19.2'

## 배열 입출력


|함수|설명|파일 종류|
|:--|:--|:--:|
|`np.save()`|NumPy 배열 객체 1개를 파일에 저장|바이너리|
|`np.savez()`|NumPy 배열 객체 여러개를 파일에 저장|바이너리|
|`np.load()`|NumPy 배열 저장 파일로부터 객체 로딩|바이너리|
|`mp.loadtxt()`|텍스트 파일로부터 배열 로딩|텍스트|
|`np.savetxt()`|텍스트 파일에 NumPy 배열 객체 저장|텍스트|

In [17]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save('a', a2)

[[8 7 6 9 7]
 [3 8 9 3 3]
 [9 6 8 2 7]
 [6 2 8 7 1]
 [2 8 1 6 4]]


In [18]:
# COLAB
# !ls 

# Local
import os
os.listdir()

['.ipynb_checkpoints',
 'a.csv',
 'a.npy',
 'ab.npz',
 'b.csv',
 'L00_Numpy.ipynb',
 'L01_Numpy Feature.ipynb',
 'L02_Numpy ndarray.ipynb',
 'L03_Numpy info &indexing & slicing.ipynb',
 'L04_Numpy array_insert delete copy transe.ipynb',
 'L05_Numpy Broadcasting & Arithmetic Operators.ipynb',
 'L06_Numpy Aggregate Functions.ipynb',
 'L07_Numpy Comparison Operators.ipynb',
 'L08_Numpy sort & argsort & partition.ipynb',
 'L09_Numpy load & save array.ipynb']

In [19]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez("ab", a2, b2)


[[6 7 1 3 2]
 [1 9 4 2 3]
 [7 8 6 8 9]
 [4 7 7 4 1]
 [3 1 4 9 6]]


In [20]:
# COLAB
# !ls 

# Local
import os
os.listdir()

['.ipynb_checkpoints',
 'a.csv',
 'a.npy',
 'ab.npz',
 'b.csv',
 'L00_Numpy.ipynb',
 'L01_Numpy Feature.ipynb',
 'L02_Numpy ndarray.ipynb',
 'L03_Numpy info &indexing & slicing.ipynb',
 'L04_Numpy array_insert delete copy transe.ipynb',
 'L05_Numpy Broadcasting & Arithmetic Operators.ipynb',
 'L06_Numpy Aggregate Functions.ipynb',
 'L07_Numpy Comparison Operators.ipynb',
 'L08_Numpy sort & argsort & partition.ipynb',
 'L09_Numpy load & save array.ipynb']

In [21]:
npy = np.load('a.npy')
npy

array([[8, 7, 6, 9, 7],
       [3, 8, 9, 3, 3],
       [9, 6, 8, 2, 7],
       [6, 2, 8, 7, 1],
       [2, 8, 1, 6, 4]])

In [22]:
npz = np.load('ab.npz')
print(npz.files)

['arr_0', 'arr_1']


In [23]:
npz['arr_0']

array([[8, 7, 6, 9, 7],
       [3, 8, 9, 3, 3],
       [9, 6, 8, 2, 7],
       [6, 2, 8, 7, 1],
       [2, 8, 1, 6, 4]])

In [24]:
print(a2)
np.savetxt("a.csv", a2, delimiter=',') # csv 파일이니까 , 로 설정

[[8 7 6 9 7]
 [3 8 9 3 3]
 [9 6 8 2 7]
 [6 2 8 7 1]
 [2 8 1 6 4]]


In [25]:
# COLAB
# !ls 

# Local
import os
os.listdir()

['.ipynb_checkpoints',
 'a.csv',
 'a.npy',
 'ab.npz',
 'b.csv',
 'L00_Numpy.ipynb',
 'L01_Numpy Feature.ipynb',
 'L02_Numpy ndarray.ipynb',
 'L03_Numpy info &indexing & slicing.ipynb',
 'L04_Numpy array_insert delete copy transe.ipynb',
 'L05_Numpy Broadcasting & Arithmetic Operators.ipynb',
 'L06_Numpy Aggregate Functions.ipynb',
 'L07_Numpy Comparison Operators.ipynb',
 'L08_Numpy sort & argsort & partition.ipynb',
 'L09_Numpy load & save array.ipynb']

In [26]:
f = open("a.csv", 'r')
for i in f:
    print(i)
f.close()

8.000000000000000000e+00,7.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00,7.000000000000000000e+00

3.000000000000000000e+00,8.000000000000000000e+00,9.000000000000000000e+00,3.000000000000000000e+00,3.000000000000000000e+00

9.000000000000000000e+00,6.000000000000000000e+00,8.000000000000000000e+00,2.000000000000000000e+00,7.000000000000000000e+00

6.000000000000000000e+00,2.000000000000000000e+00,8.000000000000000000e+00,7.000000000000000000e+00,1.000000000000000000e+00

2.000000000000000000e+00,8.000000000000000000e+00,1.000000000000000000e+00,6.000000000000000000e+00,4.000000000000000000e+00



In [27]:
csv = np.loadtxt('a.csv', delimiter=',')
csv

array([[8., 7., 6., 9., 7.],
       [3., 8., 9., 3., 3.],
       [9., 6., 8., 2., 7.],
       [6., 2., 8., 7., 1.],
       [2., 8., 1., 6., 4.]])

In [28]:
print(b2)
np.savetxt("b.csv", b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5') # fmt 소숫점 자릿수,

[[6 7 1 3 2]
 [1 9 4 2 3]
 [7 8 6 8 9]
 [4 7 7 4 1]
 [3 1 4 9 6]]


In [29]:
f = open("b.csv", 'r')
for i in f:
    print(i)
f.close()

# c1, c2, c3, c4, c5

6.00e+00,7.00e+00,1.00e+00,3.00e+00,2.00e+00

1.00e+00,9.00e+00,4.00e+00,2.00e+00,3.00e+00

7.00e+00,8.00e+00,6.00e+00,8.00e+00,9.00e+00

4.00e+00,7.00e+00,7.00e+00,4.00e+00,1.00e+00

3.00e+00,1.00e+00,4.00e+00,9.00e+00,6.00e+00



In [30]:
csv = np.loadtxt('b.csv', delimiter=',')
print(csv)

[[6. 7. 1. 3. 2.]
 [1. 9. 4. 2. 3.]
 [7. 8. 6. 8. 9.]
 [4. 7. 7. 4. 1.]
 [3. 1. 4. 9. 6.]]




---



출처:

* <a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


<br>

* [TeamLab](https://www.youtube.com/watch?v=aHthqCgsSFs&list=PLBHVuYlKEkULZLnKLzRq1CnNBOBlBTkqp)

* [이수안컴퓨터연구소](https://www.youtube.com/watch?v=mirZPrWwvao&list=PL7ZVZgsnLwEEZcVusN-fV_sJhQHq833OS&index=1)