<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


In [1]:
import numpy as np

# Set functions

1차원 ndarray 집합에 대해서


|function|설명|
|:-|:-|
|`unique(x)`|배열 내 중복된 원소 제거 후 유일한 원소를 정렬하여 반환|
|`intersect1d(x, y)`|두 개의 배열 x, y 의 교집합을 정렬하여 반환|
|`union1d(x, y)`|두 개의 배열 x, y의 합집합을 정렬하여 반환|
|`in1d(x, y)`|첫번째 배열 x가 두번째 배열 y의 원소를 포함하고 있는지 여부의 불리언 배열을 반환|
|`setdiff1d(x, y)`|첫번째 배열 x로 부터 두번째 배열 y를 뺀 차집합을 반환|
|`setxor1d(x, y)`|두 배열 x, y의 합집합에서 교집합을 뺀 대칭차집합을 반환|

<img src='https://t1.daumcdn.net/cfile/tistory/99C9173B5AFCF1C516' width='500' />

출처 : https://rfriend.tistory.com/355

## `np.unique(x)` : 배열 내 중복된 원소 제거 후 유일한 원소를 정렬하여 반환

In [2]:
x = np.array([1, 2, 3, 1, 2, 4])
np.unique(x)

array([1, 2, 3, 4])

참고로, pure python의 `sorted(set(x))` 와 `np.unique(x)` 는 동일합니다.

In [3]:
sorted(set(x))

[1, 2, 3, 4]

## `np.intersect1d(x, y)` : 두 개의 배열 x, y 의 교집합을 정렬하여 반환

In [4]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 6, 5])
np.intersect1d(x, y)

array([3, 4])

## `np.union1d(x, y)` : 두 개의 배열 x, y의 합집합을 정렬하여 반환

In [5]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 6, 5])
np.union1d(x, y)

array([1, 2, 3, 4, 5, 6])

## `np.in1d(x, y)` : 첫번째 배열이 두번째 배열의 원소를 포함하고 있는지 여부의                        불리언 배열을 반환

In [6]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([2, 4])
np.in1d(x, y)

array([False,  True, False,  True, False, False])

## `np.setdiff1d(x, y)` : 첫번째 배열 x로 부터 두번째 배열 y를 뺀 차집합을 반환

In [7]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 5, 6])
np.setdiff1d(x, y)

array([1, 2])

## `np.setxor1d(x, y)` : 두 배열 x, y의 합집합에서 교집합을 뺀 대칭차집합을 반환

In [8]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 5, 6])
np.setxor1d(x, y)

array([1, 2, 5, 6])

**Reference**

* <a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>

<br>

* [R friend](https://rfriend.tistory.com/355)