<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


출처 : https://www.w3resource.com/python-exercises/pandas/index-data-series.php

In [1]:
import pandas as pd
import numpy as np

pd.__version__

'1.1.3'

# 1. Write a Pandas program to create and display a one-dimensional array-like     
    object containing an array of data using Pandas module. 

In [2]:
s  = pd.Series([1, 3, 4, 6, 7, 9])
s

0    1
1    3
2    4
3    6
4    7
5    9
dtype: int64

# 2. Write a Pandas program to convert a Panda module Series to Python list and it's type.

In [3]:
print(type(s))
l = s.tolist()
print(l)
print(type(l))
l

<class 'pandas.core.series.Series'>
[1, 3, 4, 6, 7, 9]
<class 'list'>


[1, 3, 4, 6, 7, 9]

# 3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.     

Sample Series: `[2, 4, 6, 8, 10]`, `[1, 3, 5, 7, 9]`    
   

In [4]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])
s1, s2

(0     2
 1     4
 2     6
 3     8
 4    10
 dtype: int64,
 0    1
 1    3
 2    5
 3    7
 4    9
 dtype: int64)

In [5]:
s1.add(s2)

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [6]:
s1.sub(s2)

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [7]:
s1.mul(s2)

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [8]:
s1.divide(s2)

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [9]:
s2.divide(s1)

0    0.500000
1    0.750000
2    0.833333
3    0.875000
4    0.900000
dtype: float64

# 4. Write a Pandas program to compare the elements of the two Pandas Series.     

Sample Series: `[2, 4, 6, 8, 10]`, `[1, 3, 5, 7, 10]`    

In [10]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

s1 > s2

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [11]:
s1 < s2

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [12]:
s1 == s2

0    False
1    False
2    False
3    False
4    False
dtype: bool

# 5. Write a Pandas program to convert a dictionary to a Pandas series.     

Sample Series:    

Original dictionary:    
`{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}`

```
Converted series:    
a 100    
b 200    
c 300    
d 400    
e 800    
dtype: int64  
```
    

In [13]:
s = pd.Series({'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800})
s

a    100
b    200
c    300
d    400
e    800
dtype: int64

# 6. Write a Pandas program to convert a NumPy array to a Pandas series.    

Sample Series:    


NumPy array:    
`[10 20 30 40 50]`    


```
Converted Pandas series:    
0 10    
1 20    
2 30    
3 40    
4 50    
dtype: int64  
```
    
    

In [14]:
n_array = np.array([10, 20, 30, 40, 50])

s = pd.Series(n_array)
s

0    10
1    20
2    30
3    40
4    50
dtype: int32

# 7. Write a Pandas program to change the data type of given a column or a Series.     

Sample Series:    

```
Original Data Series:    
0 100    
1 200    
2 python    
3 300.12    
4 400    
dtype: object    
```

```
Change the said data type to numeric:    
0 100.00    
1 200.00    
2 NaN    
3 300.12    
4 400.00    
dtype: float64    
```
    

In [15]:
Original_s = pd.Series([100, 200, 'python', 300.12, 400])
Original_s

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [16]:
Original_s[2] = np.NaN

In [17]:
New_s = pd.Series(Original_s, dtype='float64')
New_s

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

# 8. Write a Pandas program to convert the first column of a DataFrame as a Series.     

Sample Output:    

```
Original DataFrame    
col1 col2 col3    
0 1 4 7    
1 2 5 5    
2 3 6 8    
3 4 9 12    
4 7 5 1    
5 11 0 11    
```

```
1st column as a Series:    
0 1    
1 2    
2 3    
3 4    
4 7    
5 11    
Name: col1, dtype: int64    
<class 'pandas.core.series.Series'>   
```
    

In [18]:
n_l = [[ 1, 4, 7],
       [ 2, 5, 5],
       [ 3, 6, 8],
       [ 4, 9, 12],
       [ 7, 5, 1],
       [ 11, 0, 11 ]]
df =pd.DataFrame(n_l, columns=['col1','col2','col3'])
df
        


col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

In [19]:
df.col1

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64

# 9. Write a Pandas program to convert a given Series to an array.     

Sample Output:    

```
Original Data Series:    
0 100    
1 200    
2 python    
3 300.12    
4 400    
dtype: object
```

```
Series to an array    
['100' '200' 'python' '300.12' '400']    
```

In [20]:
s = pd.Series([100, 200, 'python', 300.12, 400])

s_array = np.array(s)
s_array

array([100, 200, 'python', 300.12, 400], dtype=object)

# 10. Write a Pandas program to convert Series of lists to one Series.     

Sample Output:    

```
Original Series of list    
0 [Red, Green, White]    
1 [Red, Black]    
2 [Yellow]    
dtype: object    

```

```
One Series    
0 Red    
1 Green    
2 White    
3 Red    
4 Black    
5 Yellow    
dtype: object    

```

In [21]:
s = pd.Series([['Red', 'Green', 'White'], ['Red', 'Black'], ['Yellow']])
s


0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

In [22]:
new_s = []
for i in s:
    for j in i:
        new_s.append(j)
        
new_s = pd.Series(new_s)
new_s

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

# 11. Write a Pandas program to sort a given Series.     

Sample Output: 

```
Original Data Series:
0 100    
1 200    
2 python    
3 300.12    
4 400    
dtype: object   

0 100    
1 200    
3 300.12    
4 400    
2 python    
dtype: object   
```
    

In [23]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
s


0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [24]:
s.sort_values()

0       100
1       200
3    300.12
4       400
2    python
dtype: object

# 12. Write a Pandas program to add some data to an existing Series.     
Sample Output:    

```
Original Data Series:    
0 100    
1 200    
2 python    
3 300.12    
4 400    
dtype: object    

Data Series after adding some data:    
0 100    
1 200    
2 python    
3 300.12    
4 400    
0 500    
1 php    
dtype: object    
```
    

In [25]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
s

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [26]:
s2 = pd.Series(['500', 'php'])
s.append(s2)

0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

# 13. Write a Pandas program to create a subset of a given series based on value and condition.     
Sample Output:   

```
Original Data Series:    
0 0    
1 1    
2 2    
3 3    
4 4    
5 5    
6 6    
7 7    
8 8    
9 9    
10 10    
dtype: int64    

Subset of the above Data Series:    
0 0    
1 1    
2 2    
3 3    
4 4    
5 5    
dtype: int64    
```

In [27]:
s = pd.Series(range(11))
s

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [28]:
s[:6]

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

# 14. Write a Pandas program to change the order of index of a given series.   

Sample Output:    

```
Original Data Series:    
A 1    
B 2    
C 3    
D 4    
E 5    
dtype: int64    

Data Series after changing the order of index:    
B 2    
A 1    
C 3    
D 4    
E 5    
dtype: int64    
```

In [29]:
s = pd.Series(range(1,6), index=list('ABCDE'))
s

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [30]:
s[['B','A','C','D','E']]

B    2
A    1
C    3
D    4
E    5
dtype: int64

# 15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.     

```
Sample Output:    
Original Data Series:    
0 1    
1 2    
2 3    
3 4    
4 5    
5 6    
6 7    
7 8    
8 9    
9 5    
10 3    
dtype: int64    

Mean of the said Data Series:    
4.818181818181818    

Standard deviation of the said Data Series:    
2.522624895547565
```

In [31]:
s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 3])
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64

In [32]:
s.mean()

4.818181818181818

In [33]:
s.std()

2.522624895547565

# 16. Write a Pandas program to get the items of a given series not present in another given series.     

Sample Output:    

```
Original Series:    
sr1:    
0 1    
1 2    
2 3    
3 4    
4 5    
dtype: int64    

sr2:    
0 2    
1 4    
2 6    
3 8    
4 10    
dtype: int64    

Items of sr1 not present in sr2:    
0 1    
2 3    
4 5    
dtype: int64    
```    

In [34]:
sr1 = pd.Series(range(1,6))
sr2 = sr1 * 2
sr1, sr2

(0    1
 1    2
 2    3
 3    4
 4    5
 dtype: int64,
 0     2
 1     4
 2     6
 3     8
 4    10
 dtype: int64)

In [35]:
sr1[~sr1.isin(sr2)]

0    1
2    3
4    5
dtype: int64

# ★ 17. Write a Pandas program to get the items which are not common of two given series.   

Sample Output:   

```
Original Series:    
sr1:    
0 1    
1 2    
2 3    
3 4    
4 5    
dtype: int64    

sr2:    
0 2    
1 4    
2 6    
3 8    
4 10    
dtype: int64    

Items of a given series not present in another given series:    
0 1    
2 3    
4 5    
5 6    
6 8    
7 10    
dtype: int64    
```

In [36]:
sr1 = pd.Series(range(1,6))
sr2 = sr1 * 2
sr1, sr2

(0    1
 1    2
 2    3
 3    4
 4    5
 dtype: int64,
 0     2
 1     4
 2     6
 3     8
 4    10
 dtype: int64)

In [37]:
s = sr1.append(sr2).sort_values()
s[~(s.isin(sr1) & (s.isin(sr2)))]

0     1
2     3
4     5
2     6
3     8
4    10
dtype: int64

## 다른 답

In [47]:
sr1_union_sr2 = pd.Series(np.union1d(sr1, sr2))
sr1_inter_sr2 = pd.Series(np.intersect1d(sr1, sr2))

sr1_union_sr2[~sr1_union_sr2.isin(sr1_inter_sr2)]

0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64

# 18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.     

Sample Output:    

```
Original Series:    
0 3.000938    
1 11.370722    
2 14.612143    
3 8.990256    
4 13.925283    
5 12.056875    
.... 17 14.118931    
18 8.247458    
19 5.526727    
dtype: float64   


Minimum, 25th percentile, median, 75th, and maximum of a given series:    

[ 3.00093811 8.09463867 10.23353705 12.21537733 14.61214321]  
```
    

In [38]:
import numpy as np
s1 = np.random.randint(3, 20, 20)
s2 = np.random.randn(20)
s = pd.Series(s1 + s2)
s

0      7.176161
1     12.923908
2     16.156376
3     12.556301
4     14.944519
5      6.057202
6     18.291911
7      7.369007
8     14.122022
9      7.823245
10     5.671273
11     7.385653
12    11.842938
13     7.741657
14    16.888598
15    12.855808
16    18.132127
17     7.040044
18    13.854668
19    16.192285
dtype: float64

In [39]:
np.array(s.quantile([0.25, 0.5, 0.75, 1.]))

array([ 7.38149131, 12.70605442, 15.24748301, 18.29191083])

## 다른답

In [49]:
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))
print(num_series)

result = np.percentile(num_series, q=[0, 25, 50, 75, 100])
result

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64


array([ 3.00093811,  8.09463867, 10.23353705, 12.21537733, 14.61214321])

# 19. Write a Pandas program to calculate the frequency counts of each unique value of a given series.     


Sample Output:    

```
Original Series:    
0 1    
1 7    
2 1    
3 6    
4 9    
5 1    
... 29 2    
30 9    
31 1    
32 2    
33 9    
34 2    
35 9    
36 0    
37 0    
38 4    
39 8    
dtype: object    

Frequency of each unique value of the said series.    
0 9    
2 7    
9 6    
1 5    
6 3    
8 3    
7 3    
3 2    
4 1    
5 1    
dtype: int64    
```

In [40]:
import numpy as np
s = pd.Series(np.random.randint(1, 10, 40))
s

0     5
1     2
2     9
3     9
4     8
5     2
6     4
7     8
8     7
9     7
10    2
11    7
12    7
13    4
14    8
15    2
16    2
17    4
18    4
19    5
20    3
21    6
22    2
23    1
24    7
25    1
26    4
27    8
28    2
29    7
30    4
31    3
32    2
33    5
34    5
35    6
36    4
37    4
38    5
39    9
dtype: int32

In [41]:
s.value_counts()

4    8
2    8
7    6
5    5
8    4
9    3
6    2
3    2
1    2
dtype: int64

# 20. Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series.  

Sample Output:    

```
Original Series:    
0 3    
1 1    
2 1    
3 3    
4 2    
5 2    
6 1    
7 2    
8 3    
9 1    
10 2    
11 2    
12 2    
13 3    
14 3    
dtype: int64    

Top 2 Freq: 
2 6    
3 5    
1 4    
dtype: int64    
0 Other    
1 Other    
2 Other    
3 Other    
4 2    
5 2    
6 Other    
7 2    
8 Other    
9 Other    
10 2    
11 2    
12 2    
13 Other    
14 Other    
dtype: object    
```

In [42]:
s = pd.Series(np.random.randint(1, 10, 15))
s

0     3
1     6
2     3
3     1
4     7
5     1
6     8
7     1
8     1
9     9
10    4
11    1
12    3
13    9
14    8
dtype: int32

In [43]:
s.value_counts()

1    5
3    3
9    2
8    2
7    1
6    1
4    1
dtype: int64

In [44]:
s.value_counts().idxmax()

1

In [45]:
s[~(s == s.value_counts().idxmax())] ='Other'
s



0     Other
1     Other
2     Other
3         1
4     Other
5         1
6     Other
7         1
8         1
9     Other
10    Other
11        1
12    Other
13    Other
14    Other
dtype: object