<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


출처 : https://www.w3resource.com/python-exercises/pandas/index-data-series.php

In [1]:
import pandas as pd
import numpy as np

# 21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.  

Sample Output:    
```

Original Series:    
0 1    
1 9    
2 8    
3 6    
4 9    
5 7    
6 1    
7 1    
8 1    
dtype: int64    

Positions of numbers that are multiples of 5:    
[]    
```    
    

In [2]:
s = np.random.randint(1, 11, 9)
print(s)
s[s%5==0]

[ 2  6 10  4 10  1  1  9  6]


array([10, 10])

22. Write a Pandas program to extract items at given positions of a given series.     
Sample Output:    

```
Original Series:    
0 2    
1 3    
2 9    
3 0    
4 2    
5 3    
... 19 0    
20 2    
21 3    
dtype: object    


Extract items at given positions of the said series:    
0 2    
2 9    
6 8    
11 0    
21 3    
dtype: object    
```

# ★ 23. Write a Pandas program to get the positions of items of a given series in another given series.   

Sample Output:    

Original Series:    
0 1    
1 2    
2 3    
3 4    
4 5    
5 6    
6 7    
7 8    
8 9    
9 10    
dtype: int64    

0 1    
1 3    
2 5    
3 7    
4 10    
dtype: int64    

Positions of items of series2 in series1:    
[0, 2, 4, 6, 9]    
```

In [3]:
s1 = pd.Series(np.arange(1,11))
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32

In [4]:
s2 = pd.Series([1, 3, 5, 7, 10])
s2

0     1
1     3
2     5
3     7
4    10
dtype: int64

In [5]:
s1.isin(s2)

0     True
1    False
2     True
3    False
4     True
5    False
6     True
7    False
8    False
9     True
dtype: bool

In [6]:
s1.index[s1.isin(s2)]

Int64Index([0, 2, 4, 6, 9], dtype='int64')

## 다른 답안

In [7]:
[pd.Index(s1).get_loc(i) for i in s2]

[0, 2, 4, 6, 9]

# ★24. Write a Pandas program convert the first and last character of each word to upper case in each word of a given series.     

Sample Output:    

```
Original Series:    
0 php    
1 python    
2 java    
3 c#    
dtype: object    


First and last character of each word to upper case:    
0 PhP    
1 PythoN    
2 JavA    
3 C#    
dtype: object    
```
    
    

In [8]:
s1 = pd.Series(['php', 'python', 'java', 'c#'])
s1

0       php
1    python
2      java
3        c#
dtype: object

In [9]:
def upper_fnl(x):
    return (x[0]).upper() + x[1:-1] + (x[-1]).upper()
s1.apply(lambda x : upper_fnl(x))

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

## 다른답안

In [10]:
s1.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

# 25. Write a Pandas program to calculate the number of characters in each word in a given series.  

Sample Output:    

```
Original Series:    
0 Php    
1 Python    
2 Java    
3 C#    
dtype: object    

Number of characters in each word in the said series:    
0 3    
1 6    
2 4    
3 2    
dtype: int64    
    
```

In [11]:
s1 = s1.str.capitalize()
s1

0       Php
1    Python
2      Java
3        C#
dtype: object

In [12]:
s1.str.len()

0    3
1    6
2    4
3    2
dtype: int64

# 26. Write a Pandas program to compute difference of differences between consecutive numbers of a given series.     

Sample Output:    

```
Original Series:    
0 1    
1 3    
2 5    
3 8    
4 10    
5 11    
6 15    
dtype: int64    

Difference of differences between consecutive numbers of the said series:    

[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]    
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]    
```
    

In [13]:
s1 = pd.Series([1, 3, 5, 8, 10, 11, 15])
s1

0     1
1     3
2     5
3     8
4    10
5    11
6    15
dtype: int64

In [14]:
print(s1.diff().tolist())
print(s1.diff().diff().tolist())

[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]


In [15]:
np.info(np.diff)

 diff(*args, **kwargs)

Calculate the n-th discrete difference along the given axis.

The first difference is given by ``out[i] = a[i+1] - a[i]`` along
the given axis, higher differences are calculated by using `diff`
recursively.

Parameters
----------
a : array_like
    Input array
n : int, optional
    The number of times values are differenced. If zero, the input
    is returned as-is.
axis : int, optional
    The axis along which the difference is taken, default is the
    last axis.
prepend, append : array_like, optional
    Values to prepend or append to `a` along axis prior to
    performing the difference.  Scalar values are expanded to
    arrays with length 1 in the direction of axis and the shape
    of the input array in along all other axes.  Otherwise the
    dimension and shape must match `a` except along axis.

    .. versionadded:: 1.16.0

Returns
-------
diff : ndarray
    The n-th differences. The shape of the output is the same as `a`
    except along `axis` where 

# 27. Write a Pandas program to convert a series of date strings to a timeseries.     

Sample Output:    

```
Original Series:    
0 01 Jan 2015    
1 10-02-2016    
2 20180307    
3 2014/05/06    
4 2016-04-12    
5 2019-04-06T11:20    
dtype: object    

Series of date strings to a timeseries:    
0 2015-01-01 00:00:00    
1 2016-10-02 00:00:00    
2 2018-03-07 00:00:00    
3 2014-05-06 00:00:00    
4 2016-04-12 00:00:00    
5 2019-04-06 11:20:00    
dtype: datetime64[ns]    
```
    

In [16]:
s1 = pd.Series(['01 Jan 2015', '10-02-2016',
                '20180307', '2014/05/06',
                '2016-04-12', '2019-04-06T11:20'])
s1

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [17]:
pd.to_datetime(s1)

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

# ★ 28. Write a Pandas program to get the day of month, day of year, week number and day of week from a given series of date strings.  

Sample Output:    

```
Original Series:    
0 01 Jan 2015    
1 10-02-2016    
2 20180307    
3 2014/05/06    
4 2016-04-12    
5 2019-04-06T11:20    
dtype: object    

Day of month:    
[1, 2, 7, 6, 12, 6]    

Day of year:    
[1, 276, 66, 126, 103, 96]    

Week number:    
[1, 39, 10, 19, 15, 14]    

Day of week:    
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']    
```
    

In [18]:
s1 = pd.Series(['01 Jan 2015', '10-02-2016',
                '20180307', '2014/05/06',
                '2016-04-12', '2019-04-06T11:20'])

In [19]:
from dateutil.parser import parse
date_series = s1.map(lambda x: parse(x))
date_series

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

In [20]:
print("Day of month:")
print(date_series.dt.day.tolist())

print("Day of year:")
print(date_series.dt.dayofyear.tolist())

print("Week number:")
print(date_series.dt.weekofyear.tolist())

print("Day of week:")
weekday_name_list = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
print(np.array(weekday_name_list)[date_series.dt.weekday.tolist()])

Day of month:
[1, 2, 7, 6, 12, 6]
Day of year:
[1, 276, 66, 126, 103, 96]
Week number:
[1, 39, 10, 19, 15, 14]
Day of week:
['Thursday' 'Sunday' 'Wednesday' 'Tuesday' 'Tuesday' 'Saturday']


<ipython-input-20-9ca8081c1636>:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  print(date_series.dt.weekofyear.tolist())


# ★ 29. Write a Pandas program to convert year-month string to dates adding a specified day of the month.   

Sample Output:    

```
Original Series:    
0 Jan 2015    
1 Feb 2016    
2 Mar 2017    
3 Apr 2018    
4 May 2019    
dtype: object    

New dates:    
0 2015-01-11    
1 2016-02-11    
2 2017-03-11    
3 2018-04-11    
4 2019-05-11    
dtype: datetime64[ns]    
```
    

In [21]:
import pandas as pd
from dateutil.parser import parse
date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse('11 ' + d))
print(result)

Original Series:
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

New dates:
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


# 30. Write a Pandas program to filter words from a given series that contain atleast two vowels.     

Sample Output:    

```
Original Series:    
0 Red    
1 Green    
2 Orange    
3 Pink    
4 Yellow    
5 White    
dtype: object    

Filtered words:    
1 Green    
2 Orange    
4 Yellow    
5 White    
dtype: object    
```

In [22]:
s1 = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White'])
s1

0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
dtype: object

In [23]:
vowels_count = s1.str.count('a') + s1.str.count('e') + s1.str.count('i') + s1.str.count('o') \
+ s1.str.count('u') 

s1[vowels_count >=2]

1     Green
2    Orange
4    Yellow
5     White
dtype: object

다른 답안

In [24]:
import pandas as pd
from collections import Counter
color_series = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White'])
print("Original Series:")
print(color_series)
print("\nFiltered words:")
result = mask = color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
print(color_series[result])

Original Series:
0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
dtype: object

Filtered words:
1     Green
2    Orange
4    Yellow
5     White
dtype: object


# 31. Write a Pandas program to compute the Euclidean distance between two given series.     
Euclidean distance    
From Wikipedia,    
In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line distance between two points in Euclidean space. With this distance, Euclidean space becomes a metric space. The associated norm is called the Euclidean norm.    


```
Sample Output:    
Original series:    
0 1    
1 2    
2 3    
3 4    
4 5    
5 6    
6 7    
7 8    
8 9    
9 10    
dtype: int64    
0 11    
1 8    
2 7    
3 5    
4 6    
5 5    
6 3    
7 4    
8 7    
9 1    
dtype: int64    

Euclidean distance between two said series:    
16.492422502470642    
```
    

In [25]:
s1 = pd.Series(np.random.randint(1, 10, 10))
s2 = pd.Series(np.random.randint(1, 10, 10))

In [28]:
np.linalg.norm(s1 - s2)

14.730919862656235

In [29]:
np.linalg.norm?

# ★ 32. Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series.  

Sample Output:    

```
Original series:    
0 1    
1 8    
2 7    
3 5    
4 6    
5 5    
6 3    
7 4    
8 7    
9 1    
dtype: int64    

Positions of the values surrounded by smaller values on both sides:    
[1 4 8]    
  ```  
    
    

In [31]:
nums = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
nums

0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64

In [32]:
np.diff(nums)

array([ 7, -1, -2,  1, -1, -2,  1,  3, -6], dtype=int64)

In [33]:
np.sign(np.diff(nums))

array([ 1, -1, -1,  1, -1, -1,  1,  1, -1], dtype=int64)

In [34]:
np.diff(np.sign(np.diff(nums)))

array([-2,  0,  2, -2,  0,  2,  0, -2], dtype=int64)

In [35]:
temp = np.diff(np.sign(np.diff(nums)))

In [36]:
result = np.where(temp == -2)[0] + 1
print(result)

[1 4 8]


# 33. Write a Pandas program to replace missing white spaces in a given string with the least frequent character.     

Sample Output:    

```
Original series:    
abc def abcdef icd    
c 3    
d 3    
3    
b 2    
e 2    
a 2    
f 2    
i 1    
dtype: int64    

abcidefiabcdefiicd    
```
  

In [37]:
s = 'abc def abcdef icd'
s1 = pd.Series(list(s))
s1

0     a
1     b
2     c
3      
4     d
5     e
6     f
7      
8     a
9     b
10    c
11    d
12    e
13    f
14     
15    i
16    c
17    d
dtype: object

In [38]:
s1.value_counts()

d    3
c    3
     3
a    2
b    2
f    2
e    2
i    1
dtype: int64

In [39]:
s1.value_counts().idxmin()

'i'

In [40]:
s1[s1==' ']= s1.value_counts().idxmin()
s1

0     a
1     b
2     c
3     i
4     d
5     e
6     f
7     i
8     a
9     b
10    c
11    d
12    e
13    f
14    i
15    i
16    c
17    d
dtype: object

In [42]:
''.join(s1.tolist())

'abcidefiabcdefiicd'

다른답안

In [43]:
import pandas as pd
str1 = 'abc def abcdef icd'
print("Original series:")
print(str1)
ser = pd.Series(list(str1))
element_freq = ser.value_counts()
print(element_freq)
current_freq = element_freq.dropna().index[-1]
result = "".join(ser.replace(' ', current_freq))
print(result)

Original series:
abc def abcdef icd
d    3
c    3
     3
a    2
b    2
f    2
e    2
i    1
dtype: int64
abcidefiabcdefiicd


# 34. ★ Write a Pandas program to compute the autocorrelations of a given numeric series.     

From Wikipedia:    

Autocorrelation, also known as serial correlation, is the correlation of a signal with a delayed copy of itself as a function of delay. Informally, it is the similarity between observations as a function of the time lag between them.    

```
Sample Output:    
Original series:    
0 13.207262    
1 4.098685    
2 -1.435534    
3 13.626760    
... 
13 -2.346193    
14 17.873884    
dtype: float64

Autocorrelations of the said series:    
[-0.38, 0.1, -0.43, 0.03, 0.35, -0.2, 0.04, -0.59, 0.34, 0.11]    
```

In [44]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.arange(15) + np.random.normal(1, 10, 15))
print("Original series:")
print(num_series)
autocorrelations = [num_series.autocorr(i).round(2) for i in range(11)]
print("\nAutocorrelations of the said series:")
print(autocorrelations[1:])

Original series:
0      4.078328
1      1.237739
2     -6.204420
3     -9.841603
4      0.906946
5     14.200945
6     -2.525146
7      2.931368
8      7.092350
9      8.997225
10    15.064716
11    -0.547292
12     5.826397
13    23.271998
14     0.277006
dtype: float64

Autocorrelations of the said series:
[0.09, -0.18, 0.31, 0.18, 0.42, -0.34, -0.48, 0.7, -0.03, -0.5]


# ★ 35.  Write a Pandas program to create a TimeSeries to display all the Sundays of given year.     

Sample Output:    

```
All Sundays of 2020:    
0 2020-01-05    
1 2020-01-12    
2 2020-01-19    
3 2020-01-26    
4 2020-02-02    
5 2020-02-09    
..... 
48 2020-12-06    
49 2020-12-13    
50 2020-12-20    
51 2020-12-27    
dtype: datetime64[ns]    
```

In [48]:
pd.date_range('2020-01-05','2020-12-28',freq='7D')

DatetimeIndex(['2020-01-05', '2020-01-12', '2020-01-19', '2020-01-26',
               '2020-02-02', '2020-02-09', '2020-02-16', '2020-02-23',
               '2020-03-01', '2020-03-08', '2020-03-15', '2020-03-22',
               '2020-03-29', '2020-04-05', '2020-04-12', '2020-04-19',
               '2020-04-26', '2020-05-03', '2020-05-10', '2020-05-17',
               '2020-05-24', '2020-05-31', '2020-06-07', '2020-06-14',
               '2020-06-21', '2020-06-28', '2020-07-05', '2020-07-12',
               '2020-07-19', '2020-07-26', '2020-08-02', '2020-08-09',
               '2020-08-16', '2020-08-23', '2020-08-30', '2020-09-06',
               '2020-09-13', '2020-09-20', '2020-09-27', '2020-10-04',
               '2020-10-11', '2020-10-18', '2020-10-25', '2020-11-01',
               '2020-11-08', '2020-11-15', '2020-11-22', '2020-11-29',
               '2020-12-06', '2020-12-13', '2020-12-20', '2020-12-27'],
              dtype='datetime64[ns]', freq='7D')

다른 답안

In [47]:
import pandas as pd
result = pd.Series(pd.date_range('2020-01-01', periods=52, freq='W-SUN'))
print("All Sundays of 2020:")
print(result)

All Sundays of 2020:
0    2020-01-05
1    2020-01-12
2    2020-01-19
3    2020-01-26
4    2020-02-02
5    2020-02-09
6    2020-02-16
7    2020-02-23
8    2020-03-01
9    2020-03-08
10   2020-03-15
11   2020-03-22
12   2020-03-29
13   2020-04-05
14   2020-04-12
15   2020-04-19
16   2020-04-26
17   2020-05-03
18   2020-05-10
19   2020-05-17
20   2020-05-24
21   2020-05-31
22   2020-06-07
23   2020-06-14
24   2020-06-21
25   2020-06-28
26   2020-07-05
27   2020-07-12
28   2020-07-19
29   2020-07-26
30   2020-08-02
31   2020-08-09
32   2020-08-16
33   2020-08-23
34   2020-08-30
35   2020-09-06
36   2020-09-13
37   2020-09-20
38   2020-09-27
39   2020-10-04
40   2020-10-11
41   2020-10-18
42   2020-10-25
43   2020-11-01
44   2020-11-08
45   2020-11-15
46   2020-11-22
47   2020-11-29
48   2020-12-06
49   2020-12-13
50   2020-12-20
51   2020-12-27
dtype: datetime64[ns]


# ★ 36. Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe.     
Sample Output:    

```
index 0    
0 A 0    
1 B 1    
2 C 2    
3 D 3    
4 E 4    
```

In [52]:
pd.DataFrame({'index':list('ABCDE'), '0':list('01234')})

index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4

다른 답안

In [50]:
import numpy as np
import pandas as pd

char_list = list('ABCDEFGHIJKLMNOP')
num_arra = np.arange(8)
num_dict = dict(zip(char_list, num_arra))
num_ser = pd.Series(num_dict)
df = num_ser.to_frame().reset_index()
print(df.head())

  index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4


In [51]:
num_dict

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7}

# 37. Write a Pandas program to stack two given series vertically and horizontally.     

Sample Output:    

```
Original Series:    
0 0    
1 1    
2 2    
3 3    
4 4    
5 5    
6 6    
7 7    
8 8    
9 9    
dtype: int64    

0 p    
1 q    
2 r    
3 s    
4 t    
5 u    
6 v    
7 w    
8 x    
9 y    
dtype: object    

Stack two given series vertically and horizontally:    
0 1    
0 0 p    
1 1 q    
2 2 r    
3 3 s    
4 4 t    
5 5 u    
6 6 v    
7 7 w    
8 8 x    
9 9 y    
```

In [53]:
s1 = pd.Series(np.arange(10))
s2 = pd.Series(list('pqrstuvwxy'))
s1,s2

(0    0
 1    1
 2    2
 3    3
 4    4
 5    5
 6    6
 7    7
 8    8
 9    9
 dtype: int32,
 0    p
 1    q
 2    r
 3    s
 4    t
 5    u
 6    v
 7    w
 8    x
 9    y
 dtype: object)

In [56]:
# vertically
pd.concat([s1,s2])

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

In [57]:
# horizontally
pd.concat([s1,s2],axis=1)

0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y

# 38. Write a Pandas program to check the equality of two given series.     
Sample Output:    
Original Series:    
0 1    
1 8    
2 7    
3 5    
4 6    
5 5    
6 3    
7 4    
8 7    
9 1    
dtype: int64    
0 1    
1 8    
2 7    
3 5    
4 6    
5 5    
6 3    
7 4    
8 7    
9 1    
dtype: int64    
Check 2 series are equal or not?    
0 True    
1 True    
2 True    
3 True    
4 True    
5 True    
6 True    
7 True    
8 True    
9 True    
dtype: bool    

In [58]:
nums1 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
nums2 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("Original Series:")
print(nums1)
print(nums2)
print("Check 2 series are equal or not?")
print(nums1 == nums2)

Original Series:
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64
Check 2 series are equal or not?
0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool


# 39. Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series.     
Sample Output:    

```
Original Series:    
0 1    
1 3    
2 7    
3 12    
4 88    
5 23    
6 3    
7 1    
8 9    
9 0    
dtype: int64    

Index of the first occurrence of the smallest and largest value of the said series:    
9    
4    
```

In [59]:
s1 = np.random.randint(0, 100, 10)
s1

array([44, 39, 46, 52, 82, 43, 15, 78, 16, 12])

In [61]:
s1.argmin(), s1.argmax()

(9, 4)

다른 답안

In [62]:
import pandas as pd
nums = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])
print("Original Series:")
print(nums)
print("Index of the first occurrence of the smallest and largest value of the said series:")
print(nums.idxmin())
print(nums.idxmax())

Original Series:
0     1
1     3
2     7
3    12
4    88
5    23
6     3
7     1
8     9
9     0
dtype: int64
Index of the first occurrence of the smallest and largest value of the said series:
9
4


# ★ 40. Write a Pandas program to check inequality over the index axis of a given dataframe and a given series.     

Sample Output:    

```
Original DataFrame:    
W X Y Z    
0 68.0 78.0 84 86    
1 75.0 75.0 94 97    
2 86.0 NaN 89 96    
3 80.0 80.0 86 72    
4 NaN 86.0 86 83    

Original Series:    
0 68.0    
1 75.0    
2 86.0    
3 80.0    
4 NaN    
dtype: float64    

Check for inequality of the said series & dataframe:    
W X Y Z    
0 False True True True    
1 False False True True    
2 False True True True    
3 False False True True    
4 True True True True    
```

In [63]:
df_data = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,75,None,80,86], 'Y':[84,94,89,86,86],'Z':[86,97,96,72,83]});
sr_data = pd.Series([68, 75, 86, 80, None]) 

In [72]:
df_data.ne(sr_data, axis=0)

W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True

In [73]:
help(df_data.ne)

Help on method ne in module pandas.core.ops:

ne(other, axis='columns', level=None) method of pandas.core.frame.DataFrame instance
    Get Not equal to of dataframe and other, element-wise (binary operator `ne`).
    
    Among flexible wrappers (`eq`, `ne`, `le`, `lt`, `ge`, `gt`) to comparison
    operators.
    
    Equivalent to `==`, `=!`, `<=`, `<`, `>=`, `>` with support to choose axis
    (rows or columns) and level for comparison.
    
    Parameters
    ----------
    other : scalar, sequence, Series, or DataFrame
        Any single or multiple element data structure, or list-like object.
    axis : {0 or 'index', 1 or 'columns'}, default 'columns'
        Whether to compare by the index (0 or 'index') or columns
        (1 or 'columns').
    level : int or label
        Broadcast across a level, matching Index values on the passed
        MultiIndex level.
    
    Returns
    -------
    DataFrame of bool
        Result of the comparison.
    
    See Also
    --------
    