In [5]:
import numpy as np
np.__version__

'1.19.2'

# 배열 조회

## 배열 속성 정보

In [6]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
a3 = np.array([ [ [1,2,3], [4, 5, 6], [7, 8, 9] ],
                [ [1,2,3], [4, 5, 6], [7, 8, 9] ],
                [ [1,2,3], [4, 5, 6], [7, 8, 9] ] ])


In [7]:
def array_info(array):
    print('info of array')
    print(array)
    print("ndim", array.ndim)
    print("shape:", array.shape)
    print("dtype:", array.dtype)
    print("size:",array.size)
    print("itmesize:", array.itemsize)
    print("nbytes:", array.nbytes)
    print("strides:", array.strides)

In [8]:
array_info(a1)

info of array
[1 2 3 4 5]
ndim 1
shape: (5,)
dtype: int32
size: 5
itmesize: 4
nbytes: 20
strides: (4,)


[9 2 3 4 5]    
ndim 1   
shape: (5,)     
dtype: int32  # 데이터 타입   
size: 5   # 몇개?   
itmesize: 4  # 1개 가지는 용량 size // int32 이니까 4bytes   
nbytes: 20    # size * itemsize   
strides: (4,) # 1개의 차원을 넘어가는데 드는 비용?! 확인 필   

In [9]:
array_info(a2)

info of array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim 2
shape: (3, 3)
dtype: int32
size: 9
itmesize: 4
nbytes: 36
strides: (12, 4)


In [10]:
array_info(a3)

info of array
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim 3
shape: (3, 3, 3)
dtype: int32
size: 27
itmesize: 4
nbytes: 108
strides: (36, 12, 4)


## 인덱싱(Indexing)

In [11]:
print(a1)
print(a1[1])
print(a1[-1])

[1 2 3 4 5]
2
5


In [12]:
print(a2)
print(a2[0])
print(a2[0, 2])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
3
9


In [13]:
print(a3)
print(a3[0])
print(a3[-1,2])
print(a3[0, 0, 0])
print(a3[2, -1, -1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
1
9


## 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [14]:
print(a1)
print(a1[0:2])
print(a1[:1])
print(a1[::2])
print(a1[::-1]) # 역순

[1 2 3 4 5]
[1 2]
[1]
[1 3 5]
[5 4 3 2 1]


In [15]:
print(a2)
print('print(a2[1])')
print(a2[1])
print('print(a2[1, :])')
print(a2[1, :])
print('print(a2[:2, :2])')
print(a2[:2, :2])
print('print(a2[1:, ::-1])')
print(a2[1:, ::-1])
print('print(a2[::-1, ::-1])')
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
print(a2[1])
[4 5 6]
print(a2[1, :])
[4 5 6]
print(a2[:2, :2])
[[1 2]
 [4 5]]
print(a2[1:, ::-1])
[[6 5 4]
 [9 8 7]]
print(a2[::-1, ::-1])
[[9 8 7]
 [6 5 4]
 [3 2 1]]


## 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [16]:
print(a1)
bi = [False, True, True, False, False]
print(a1[bi])
array_info(a1[bi])

[1 2 3 4 5]
[2 3]
info of array
[2 3]
ndim 1
shape: (2,)
dtype: int32
size: 2
itmesize: 4
nbytes: 8
strides: (4,)


In [17]:
print(a2)
bi = np.random.randint(0,2, (3,3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True False False]
 [ True False False]
 [ True False  True]]
[1 4 7 9]


## 팬시 인덱싱(Fancy Indedxing)

In [18]:
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])

[1 2 3 4 5]
[1, 3]
[1 3]


fancy index 로 나온 결과의 결과값의 shape는 ind 와 동일하다.

In [19]:
ind =np.array([[0, 1],
               [2, 0]])

print(a1[ind])

[[1 2]
 [3 1]]


In [20]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]


In [21]:
print(a2[row, :])
print(a2[:, col])
print(a2[2, col])
print(a2[1:, col])

[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[8 9]
[[5 6]
 [8 9]]




---

