In [1]:
import numpy as np
np.__version__

'1.19.2'

### 배열 정렬

In [7]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)
a1.sort()
print(a1)

[2 7 7 8 6 2 2 9 4 6]
[2 2 2 4 6 6 7 7 8 9]
[2 7 7 8 6 2 2 9 4 6]
[0 5 6 8 4 9 1 2 3 7]
[2 7 7 8 6 2 2 9 4 6]
[2 2 2 4 6 6 7 7 8 9]


In [8]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[5 7 7]
 [1 5 8]
 [9 9 1]]
[[1 5 1]
 [5 7 7]
 [9 9 8]]
[[5 7 7]
 [1 5 8]
 [1 9 9]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [9]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3))

[5 1 7 9 4 7 1 3 4 8]
[1 1 3 4 4 5 7 9 7 8]


In [10]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))


[[8 3 5 3 1]
 [6 1 2 7 7]
 [8 9 1 1 4]
 [5 2 2 7 1]
 [1 2 7 8 7]]
[[3 1 3 5 8]
 [1 2 6 7 7]
 [1 1 4 8 9]
 [1 2 2 5 7]
 [2 1 7 7 8]]
[[5 2 2 1 1]
 [1 2 1 3 1]
 [6 1 2 7 4]
 [8 3 5 7 7]
 [8 9 7 8 7]]
[[3 1 3 5 8]
 [1 2 6 7 7]
 [1 1 4 8 9]
 [1 2 2 5 7]
 [2 1 7 7 8]]
