<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


출처:https://www.w3resource.com/python-exercises/numpy/basic/index.php

# 1.Write a NumPy program to get the numpy version and show numpy build configuration.

In [4]:
import numpy as np

print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bigne/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/bigne/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bigne/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/bigne/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bigne/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/bigne/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bigne/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/bigne/anaconda3\\Library\\include']
None


# 2. Write a NumPy program to  get help on the add function.     

In [5]:
np.add?

In [6]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [7]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# 3. Write a NumPy program to test whether none of the elements of a given array is zero.     

In [8]:
array = np.array([1, 2, 3, 0, 0])

array==0

array([False, False, False,  True,  True])

# 4. Write a NumPy program to test whether any of the elements of a given array is non-zero.     

In [9]:
array = np.array([1, 2, 3, 0, 0])

array != 0

array([ True,  True,  True, False, False])

# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).     

In [10]:
array = np.array([1, 2, np.inf, np.NaN])
array

array([ 1.,  2., inf, nan])

In [11]:
np.isnan(array)

array([False, False, False,  True])

In [12]:
np.isinf(array)

array([False, False,  True, False])

# 6. Write a NumPy program to test element-wise for positive or negative infinity.     

In [13]:
np.*inf?

In [14]:
array = np.array([1, 2, np.inf, np.NaN, -np.inf])
array

array([  1.,   2.,  inf,  nan, -inf])

In [15]:
np.isinf(array)

array([False, False,  True, False,  True])

In [16]:
np.isneginf(array)

array([False, False, False, False,  True])

In [17]:
# 양의 무한대만 찾고 싶다면?
(np.isinf(array)) & (np.greater(array, 0))

array([False, False,  True, False, False])

# 7. Write a NumPy program to test element-wise for NaN of a given array.     

In [18]:
array = np.array([1, 2, np.inf, np.NaN, -np.inf])

np.isnan(array)

array([False, False, False,  True, False])

# 8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.     
    
    

In [19]:
s = np.array([1+3j, 1-3j, -1+2j, 3+2j])
print(s.dtype)
s

complex128


array([ 1.+3.j,  1.-3.j, -1.+2.j,  3.+2.j])

In [20]:
s.real

array([ 1.,  1., -1.,  3.])

In [21]:
s.imag

array([ 3., -3.,  2.,  2.])

In [22]:
np.isscalar(array)

False

# 9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.     
    
    

In [23]:
array1 = np.array([1, 2, np.inf, np.NaN, -np.inf])
array2 = np.array([1, 2, np.inf, np.NaN, 5])

np.equal(array1, array2)

array([ True,  True,  True, False, False])

# 10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.     
    
    

In [24]:
array1 = np.array(np.random.randint(1,10,10))
array2 = np.array(np.random.randint(1,10,10))

array1, array2

(array([1, 2, 7, 4, 6, 7, 5, 9, 1, 5]), array([4, 2, 2, 8, 7, 6, 1, 8, 6, 3]))

In [25]:
np.greater(array1, array2)


array([False, False,  True, False, False,  True,  True,  True, False,
        True])

In [26]:
np.greater_equal(array1, array2)

array([False,  True,  True, False, False,  True,  True,  True, False,
        True])

In [27]:
np.less(array1, array2)

array([ True, False, False,  True,  True, False, False, False,  True,
       False])

In [28]:
np.less_equal(array1, array2)

array([ True,  True, False,  True,  True, False, False, False,  True,
       False])

# 11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays. 

In [29]:
array1 = np.array(np.random.randint(1,5,10))
array2 = np.array(np.random.randint(1,5,10))

array1, array2

(array([3, 2, 3, 2, 2, 1, 2, 1, 2, 3]), array([2, 2, 1, 1, 2, 2, 2, 4, 4, 3]))

In [30]:
np.equal(array1, array2)

array([False,  True, False, False,  True, False,  True, False, False,
        True])

In [31]:
array1 == array2

array([False,  True, False, False,  True, False,  True, False, False,
        True])

In [33]:
np.info(np.allclose)

 allclose(*args, **kwargs)

Returns True if two arrays are element-wise equal within a tolerance.

The tolerance values are positive, typically very small numbers.  The
relative difference (`rtol` * abs(`b`)) and the absolute difference
`atol` are added together to compare against the absolute difference
between `a` and `b`.

NaNs are treated as equal if they are in the same place and if
``equal_nan=True``.  Infs are treated as equal if they are in the same
place and of the same sign in both arrays.

Parameters
----------
a, b : array_like
    Input arrays to compare.
rtol : float
    The relative tolerance parameter (see Notes).
atol : float
    The absolute tolerance parameter (see Notes).
equal_nan : bool
    Whether to compare NaN's as equal.  If True, NaN's in `a` will be
    considered equal to NaN's in `b` in the output array.

    .. versionadded:: 1.10.0

Returns
-------
allclose : bool
    Returns True if the two arrays are equal within the given
    tolerance; False otherwis

In [32]:
# equal within a tolerance
np.allclose(array1, array2)

False

# 12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.     
    
    

In [35]:
array = np.array([1, 7, 13, 105])
array


array([  1,   7,  13, 105])

In [38]:
print(array.nbytes * array.size)

64


# 13. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives. 

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 14. Write a NumPy program to create an array of the integers from 30 to70.     
    
    

In [43]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

# 15. Write a NumPy program to create an array of all the even integers from 30 to 70.     
    
    

In [44]:
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

# 16. Write a NumPy program to create a 3x3 identity matrix.     
    
    

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 17. Write a NumPy program to generate a random number between 0 and 1.     
    
    

In [46]:
np.random.uniform(0,1, 10)

array([0.33024178, 0.60096336, 0.75920264, 0.19253619, 0.32618518,
       0.01469524, 0.00224448, 0.14516911, 0.54328614, 0.61572819])

# 18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.     
    
    

In [47]:
np.random.randn(15)

array([-0.99917565, -1.37664996,  1.0031081 , -1.37873858,  0.57074962,
        1.13098425, -0.23708745,  2.19488631, -0.11108502, -0.8655196 ,
        0.39347901,  0.45626542, -0.49760854, -0.14048519, -1.16248842])

# 19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.     
    
    

In [49]:
np.arange(15, 56)[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

# 20. Write a NumPy program to create a 3X4 array using and iterate over it.     
    

In [55]:
s = np.array([np.arange(4) for a in range(3)])

In [56]:
s

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [57]:
s.shape

(3, 4)

정답

In [34]:
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [36]:
print("Each element of the array is:")
for x in np.nditer(a):
    print(x, end=" ")

Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [37]:
np.info(np.nditer)

 nditer()

nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``copy_if_overlap`` causes the iterator to determine if read
