<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


출처:https://www.w3resource.com/python-exercises/numpy/basic/index.php

In [1]:
import numpy as np

# 41. Write a NumPy program to convert numpy dtypes to native python types.     
    

In [2]:
print("numpy.float32 to python float")
x = np.float32(0)
print(type(x))
pyval = x.item()
print(type(pyval))

numpy.float32 to python float
<class 'numpy.float32'>
<class 'float'>


# 42. Write a NumPy program to add elements in a matrix. If an element in the matrix is 0, we will not add the element below this element.     
    

In [3]:
def special_sum_0(array_o):
    array = array_o.copy()
    result = 0 
    p_, q_ = array.shape
    for p in range(p_):
        for q in range(q_):
            if array_o[p][q] == 0 :
                try:
                    array[p+1][q] = 0 
                except:
                    pass
                
            result += array[p][q]
            
    return result

In [4]:
ar=np.random.randint(0,10,(3,4))
ar

array([[4, 4, 2, 1],
       [1, 5, 7, 1],
       [6, 3, 1, 1]])

In [5]:
np.sum(ar)

36

In [6]:
special_sum_0(ar)

36

제시한 정답 및 수정

* 문제에서 제시한 정답대로 실행 할 시에는 바로 밑에 있는 숫자만 더하지 않은 것이 아니라 모든 아래에 있는 숫자를 더하지 않게된다. 

* 영어로 인한 해석?!의 이해도가 떨ㅇㅓ져서 무엇이 원하는 것인지는 생각해보기를~

In [7]:
import numpy as np
def sum_matrix_Elements(m):
    arra = np.array(m)   
    element_sum = 0  
    for p in range(len(arra)):  
        for q in range(len(arra[p])):  
            if arra[p][q] == 0 and p < len(arra)-1: 
                arra[p+1][q] = 0  
            element_sum += arra[p][q]  
    return element_sum
m = [[1, 1, 0, 2],
     [0, 3, 0, 3], 
     [1, 0, 4, 4]]
print("Original matrix:")
print(m)
print("Sum:")
print(sum_matrix_Elements(m))

Original matrix:
[[1, 1, 0, 2], [0, 3, 0, 3], [1, 0, 4, 4]]
Sum:
14


# 43. Write a NumPy program to find the missing data in a given array.        
    

In [8]:
array1 = np.array([1, 3, np.nan, 5, np.nan])
np.isnan(array1)

array([False, False,  True, False,  True])

# 44. Write a NumPy program to check whether two arrays are equal (element wise) or not.     
    
    

In [9]:
array1 = np.random.randint(1, 4, 5)
array2 = np.random.randint(1, 4, 5)

np.equal(array1, array2)

array([False, False, False, False, False])

# 45. Write a NumPy program to create one-dimensional array of single, two and three digit numbers.     
    
    

In [10]:
nums = np.arange(1, 21)
print("One-dimensional array of single digit numbers:") 
print(nums)
nums = np.arange(10, 21)
print("\nOne-dimensional array of two digit numbers:") 
print(nums)
nums = np.arange(100, 201)
print("\nOne-dimensional array of three digit numbers:") 
print(nums)

One-dimensional array of single digit numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

One-dimensional array of two digit numbers:
[10 11 12 13 14 15 16 17 18 19 20]

One-dimensional array of three digit numbers:
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


# 46. Write a NumPy program to create a two-dimensional array of specified format.     
    
    

In [11]:
array1 = np.arange(30)
array1.reshape(-2,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

# 47. Write a NumPy program to create a one dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1.     
    
    

In [12]:
array1 = np.random.uniform(0,1, 10)
array1

array([0.58861076, 0.35713665, 0.44834677, 0.51861264, 0.86830025,
       0.33664332, 0.05422178, 0.87617367, 0.17440728, 0.3636408 ])

In [13]:
# or

np.random.rand(10)

array([0.02055954, 0.29922818, 0.27219986, 0.19858521, 0.1170148 ,
       0.91229989, 0.61939287, 0.64470972, 0.51786098, 0.46212041])

# 48. Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).     
    
    

In [14]:
np.random.normal(200, 7,(8,5))

array([[200.1439801 , 186.85904102, 206.52338131, 201.85158449,
        208.74584548],
       [205.15539659, 195.68660552, 195.89685217, 197.54942477,
        195.81489437],
       [199.01223025, 194.65033744, 200.31016446, 189.71505384,
        195.49348723],
       [193.29180009, 199.82787324, 203.43077673, 196.74476659,
        195.18772684],
       [193.8648271 , 188.16206949, 194.44490135, 199.25580047,
        195.70051421],
       [199.6633218 , 195.97768086, 199.48152323, 209.54660566,
        202.2259287 ],
       [204.26173496, 199.64638593, 213.79251792, 199.00415601,
        214.01672227],
       [204.66321639, 202.6107178 , 204.28096045, 189.07928656,
        181.86236068]])

다른 답안

In [15]:
import numpy as np 
np.random.seed(20) 
cbrt = np.cbrt(7)
nd1 = 200 
print(cbrt * np.random.randn(10, 4) + nd1) 

[[201.6908267  200.37467631 200.68394275 195.51750123]
 [197.92478992 201.07066048 201.79714021 198.1282331 ]
 [200.96238963 200.77744291 200.61875865 199.05613894]
 [198.48492638 198.38860811 197.55239946 200.47003621]
 [199.91545839 202.99877319 202.01069857 200.77735483]
 [199.67739161 193.89831807 202.14273593 202.54951299]
 [199.53450969 199.7512602  199.79145727 202.97687757]
 [200.24634413 196.04606934 198.30611253 197.88701546]
 [201.78450912 203.94032834 198.21152803 196.91446071]
 [201.0082481  197.03285104 200.63052763 197.82590294]]


In [16]:
cbrt

1.9129311827723892

In [17]:
np.info(np.cbrt)

cbrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the cube-root of an array, element-wise.

.. versionadded:: 1.10.0

Parameters
----------
x : array_like
    The values whose cube-roots are required.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    r

# ★ 49. Write a NumPy program to generate a uniform, non-uniform random sample from a given 1-D array with and without replacement.     
    
    

In [18]:
import numpy as np 
print("Generate a uniform random sample with replacement:") 
print(np.random.choice(7, 5))
print("\nGenerate a uniform random sample without replacement:") 
print(np.random.choice(7, 5, replace=False))
print("\nGenerate a non-uniform random sample with replacement:") 
print(np.random.choice(7, 5, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))
print("\nGenerate a uniform random sample without replacement:") 
print(np.random.choice(7, 5, replace=False, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))

Generate a uniform random sample with replacement:
[2 2 1 5 2]

Generate a uniform random sample without replacement:
[6 3 5 4 2]

Generate a non-uniform random sample with replacement:
[6 1 6 0 1]

Generate a uniform random sample without replacement:
[1 6 4 3 0]


# ★ 50. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.     
    
    

In [19]:
array1 = np.random.randn(16).reshape(4,4)
array1

array([[ 1.25170782, -1.02567366, -1.34208494,  1.52216482],
       [-0.21452092,  0.85719851,  1.0832877 , -0.46545803],
       [ 0.5385686 , -0.52748225,  0.46367221, -1.79818036],
       [ 0.59178279,  1.17407295,  1.1593503 , -0.08915085]])

In [20]:
array1 = array1[::-1]
array1

array([[ 0.59178279,  1.17407295,  1.1593503 , -0.08915085],
       [ 0.5385686 , -0.52748225,  0.46367221, -1.79818036],
       [-0.21452092,  0.85719851,  1.0832877 , -0.46545803],
       [ 1.25170782, -1.02567366, -1.34208494,  1.52216482]])

In [21]:
array1 = array1[:,::-1]
array1

array([[-0.08915085,  1.1593503 ,  1.17407295,  0.59178279],
       [-1.79818036,  0.46367221, -0.52748225,  0.5385686 ],
       [-0.46545803,  1.0832877 ,  0.85719851, -0.21452092],
       [ 1.52216482, -1.34208494, -1.02567366,  1.25170782]])

# 51. Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.    

In [22]:
np.zeros((5,6),dtype=np.int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# 52. Write a NumPy program to sort a given array by row and column in ascending order.     
    
    

In [23]:
array1 = np.random.choice((np.arange(16)),16, replace=False)
array1

array([ 4, 13, 12, 14,  7, 15,  3, 10,  0, 11,  8,  1,  6,  9,  2,  5])

In [24]:
np.sort(array)

NameError: name 'array' is not defined

In [ ]:
array2 = np.random.choice((np.arange(16)),16, replace=False).reshape(4,4)
array2

In [ ]:
np.sort(array2)

In [ ]:
np.sort(array2,axis=0)

# ★ 53. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.     
    
    

In [ ]:
array = np.random.choice((np.arange(16)),16, replace=False).reshape(4,4)
array

In [ ]:
array = np.random.choice((np.arange(16)),16, replace=False).reshape(4,4)
array
np.where(array>3)

In [ ]:
array[np.where((array>3) & (array<7))]

다른 답안

In [ ]:
import numpy as np  
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
n = 5
print("\nElements of the said array greater than",n)
print(nums[nums > n])
n = 6
print("\nElements of the said array less than",n)
print(nums[nums < n])

# ★ 54. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.     
    
    

In [ ]:
array = np.random.choice((np.arange(16)),16, replace=False).reshape(4,4)
array

In [ ]:
array[np.where((array>3) & (array<7))]=99
array

다른 답안

In [ ]:
import numpy as np
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
n = 8.32
r = 18.32
print("\nReplace elements of the said array which are equal to ",n,"with",r)
print(np.where(nums == n, r, nums))
print("\nReplace elements with of the said array which are less than",n,"with",r)
print(np.where(nums < n, r, nums))
print("\nReplace elements with of the said array which are greater than",n,"with",r)
print(np.where(nums > n, r, nums))

# 55. Write a NumPy program to create an array of equal shape and data type of a given array.     
    
    

In [25]:
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
print("\nNew array of equal shape and data type of the said array filled by 0:")
print(np.zeros_like(nums))

Original array:
[[5.54 3.38 7.99]
 [3.54 8.32 6.99]
 [1.54 2.39 9.29]]

New array of equal shape and data type of the said array filled by 0:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 56. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.     
    
    

In [26]:
array1_3d = np.array(np.arange(60)).reshape(3,5,-1)
array1_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

# 57. Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns.     
    
    

In [27]:
array1 = np.array(np.arange(16)).reshape(4,-1)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
array1[:,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

# 58. Write a NumPy program to swap rows and columns of a given array in reverse order.     
    
    

In [30]:
array1 = np.array(np.arange(16)).reshape(4,-1)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
array1[::-1,::-1]

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

# 59. Write a NumPy program to multiply two given arrays of same size element-by-element.     

In [33]:
array1 = np.array(np.arange(16)).reshape(4,-1)

array2 = np.array(np.arange(16,32)).reshape(4,-1)


In [34]:
array1 * array2

array([[  0,  17,  36,  57],
       [ 80, 105, 132, 161],
       [192, 225, 260, 297],
       [336, 377, 420, 465]])

In [35]:
np.multiply(array1, array2)

array([[  0,  17,  36,  57],
       [ 80, 105, 132, 161],
       [192, 225, 260, 297],
       [336, 377, 420, 465]])