<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


출처: https://www.w3resource.com/python-exercises/numpy/index-array.php

![array](https://www.w3resource.com/w3r_images/python-numpy-arrays-image.png)

https://www.w3resource.com/w3r_images/python-numpy-arrays-image.png

# 1. Write a NumPy program to print the NumPy version in your system.     
    

In [1]:
import numpy as np
np.__version__

'1.19.2'

# 2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.     

```
Expected Output:    

Original List: [12.23, 13.32, 100, 36.32]    
One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]    
```
    

In [2]:
l = [12.23, 13.32, 100, 36.32]
array1 = np.array(l)
array1

array([ 12.23,  13.32, 100.  ,  36.32])

# 3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.     

```
Expected Output:   

[[ 2 3 4]    
[ 5 6 7]    
[ 8 9 10]]    
```    
    

In [3]:
np.arange(2, 11).reshape(3, 3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
array1 = np.arange(2, 11).reshape(3, 3)
array1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
np.swapaxes(array1, axis1=1, axis2=0)

array([[ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]])

# 4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.    

```
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]    

Update sixth value to 11    

[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]    
```    
    

In [6]:
array1 = np.zeros(10)
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
array1[6] = 11
array1

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

# 5. Write a NumPy program to create an array with values ranging from 12 to 38.    

```
Expected Output:  

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]    
    
```    

In [8]:
np.arange(12, 38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

# 6. Write a NumPy program to reverse an array (first element becomes last).     
```
Original array:   
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]    

Reverse array:    
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]   
```
    
    

In [9]:
np.arange(12, 38)[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

# 7. Write a NumPy program to convert an array to a float type.    

```
Sample output:    

Original array    
[1, 2, 3, 4]    

Array converted to a float type:    
[ 1. 2. 3. 4.]    
```    
    

In [10]:
array1 = np.array([1, 2, 3, 4])
array1

array([1, 2, 3, 4])

In [11]:
array1.astype(np.float16)

array([1., 2., 3., 4.], dtype=float16)

# ★ 8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.    

```
Expected Output:   

Original array:    
[[ 1. 1. 1. 1. 1.]    
...................    
[ 1. 1. 1. 1. 1.]]   

1 on the border and 0 inside in the array    
[[ 1. 1. 1. 1. 1.]    
...................    
[ 1. 1. 1. 1. 1.]]    
```
    
    

In [12]:
array1 = np.zeros((5,5))
array1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
array1[:,0]= 1
array1[:, -1] = 1
array1[0, :] = 1
array1[-1, :] = 1
array1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

다른 정답

In [14]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# ★ 9. Write a NumPy program to add a border (filled with 0's) around an existing array.     

```
Expected Output:    

Original array:    
[[ 1. 1. 1.]    
[ 1. 1. 1.]    
[ 1. 1. 1.]]    

1 on the border and 0 inside in the array    
[[ 0. 0. 0. 0. 0.]    
...........    
[ 0. 0. 0. 0. 0.]] 
```
    
    

In [15]:
array1 = np.ones((3, 3))
array1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
 np.pad(array1, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
 np.pad(array1, pad_width=1, mode='edge')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.    

```
Checkerboard pattern:    

[[0 1 0 1 0 1 0 1]    
..........    
[0 1 0 1 0 1 0 1]    
[1 0 1 0 1 0 1 0]]    
```
    
    

In [18]:
array1 = np.ones((8, 8))
array1

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
array1[::2,::2]=0
array1[1::2,1::2]=0
array1

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 11. Write a NumPy program to convert a list and tuple into arrays.     

```
List to array:    
[1 2 3 4 5 6 7 8]    

Tuple to array:    
[[8 4 6]    
[1 2 3]]    
```
    
    
    

In [20]:
l = [1,2,3,4,5,6,7,8]
t = 8, 4, 6, 1, 2, 3
l,t

([1, 2, 3, 4, 5, 6, 7, 8], (8, 4, 6, 1, 2, 3))

In [21]:
array_l = np.array(l)
array_t = np.array(t).reshape(2,3)

In [22]:
array_l, array_t

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([[8, 4, 6],
        [1, 2, 3]]))

# 12. Write a NumPy program to append values to the end of an array.    

```
Expected Output:    

Original array:    
[10, 20, 30]    

After append values to the end of the array:    
[10 20 30 40 50 60 70 80 90]    
```
    
    

In [23]:
array1 = np.array([10, 20, 30])
array1

array([10, 20, 30])

In [24]:
array1

array([10, 20, 30])

In [26]:
np.append(array1,[40,50,60,70,80,90])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
np.append(array1,[[40,50,60],[70,80,90]])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# ★ 13. Write a NumPy program to create an empty and a full array.     

```
Expected Output:    

[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]    
[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]    
[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]    
[[6 6 6]    
[6 6 6]    
[6 6 6]]    
```
    
    

In [32]:
np.empty((3, 4))

array([[0.20043299, 0.20043299, 0.20043299, 0.20043299],
       [0.20043299, 0.20043299, 0.20043299, 0.20043299],
       [0.20043299, 0.20043299, 0.20043299, 0.20043299]])

In [31]:
np.full((3, 3), 6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

# 14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array. 

```
Sample Array [0, 12, 45.21 ,34, 99.91]    

Expected Output:    
Values in Fahrenheit degrees:    
[ 0. 12. 45.21 34. 99.91]    

Values in Centigrade degrees:    
[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]    
```
    
    

![Temp](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-14.png)

In [35]:
array_F = np.array([0, 12, 45,21, 34, 99,91])

(5/9)*(array_F-32)

array([-17.77777778, -11.11111111,   7.22222222,  -6.11111111,
         1.11111111,  37.22222222,  32.77777778])

# 15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.     

```
Expected Output:    

Original array [ 1.00000000+0.j 0.70710678+0.70710678j]    

Real part of the array:    
[ 1. 0.70710678]    

Imaginary part of the array:    
[ 0. 0.70710678]    
```
    
    

In [42]:
array = np.array([1.+0.j, 0.70710678 + 0.70710678j])
array

array([1.        +0.j        , 0.70710678+0.70710678j])

In [43]:
np.real(array)

array([1.        , 0.70710678])

In [44]:
np.imag(array)

array([0.        , 0.70710678])

# 16. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.     

```
Expected Output:    

Size of the array: 3    

Length of one array element in bytes: 8    

Total bytes consumed by the elements of the array: 24    
```
    
    

![array_inf](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-16.png)

In [45]:
array.size

2

In [47]:
array.itemsize

16

In [46]:
array.nbytes

32

# 17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.     

```
Expected Output:    

Array1: [ 0 10 20 40 60]    

Array2: [0, 40]    

Compare each element of array1 and array2    
[ True False False True False]    
```
    
    

In [50]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])

In [51]:
np.isin(array1, array2)

array([ True, False, False,  True, False])

# 18. Write a NumPy program to find common values between two arrays. 

```
Expected Output:    

Array1: [ 0 10 20 40 60]    

Array2: [10, 30, 40]    

Common values between two arrays:    
[10 40]    
```
    

In [52]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

np.intersect1d(array1, array2)

array([10, 40])

# 19. Write a NumPy program to get the unique elements of an array.    

```
Expected Output:    

Original array:    
[10 10 20 20 30 30]    

Unique elements of the above array:    
[10 20 30]    

Original array:    
[[1 1]    
[2 3]]    

Unique elements of the above array:    
[1 2 3]    
```
    
    

In [53]:
array1 = np.array([10, 10, 20, 30, 30])
array2 = np.array([[1, 1],[2, 3]])


In [54]:
np.unique(array1)

array([10, 20, 30])

In [55]:
np.unique(array2)

array([1, 2, 3])

# 20. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.     

```
Expected Output:    

Array1: [ 0 10 20 40 60 80]    

Array2: [10, 30, 40, 50, 70, 90]   

Set difference between two arrays:    
[ 0 20 60 80]    
```
    

In [56]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

In [57]:
np.setdiff1d(array1, array2)

array([ 0, 20, 60, 80])