<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


출처: https://www.w3resource.com/python-exercises/numpy/index-array.php

In [1]:
import numpy as np

# 21. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.     

```
Array1: [ 0 10 20 40 60 80]    
Array2: [10, 30, 40, 50, 70]    

Unique values that are in only one (not both) of the input arrays:    
[ 0 20 30 50 60 70 80]    
```
    
    

In [2]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])


In [3]:
arr_uni = np.union1d(array1, array2) 

In [4]:
arr_inter = np.intersect1d(array1, array2)

In [5]:
np.setdiff1d(arr_uni, arr_inter)

array([ 0, 20, 30, 50, 60, 70, 80])

다른 답안

In [6]:
np.setxor1d(array1, array2)

array([ 0, 20, 30, 50, 60, 70, 80])

# 22. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.     

```
Array1: [ 0 10 20 40 60 80]    
Array2: [10, 30, 40, 50, 70]    

Unique sorted array of values that are in either of the two input arrays:    
[ 0 10 20 30 40 50 60 70 80]    
```
    

In [7]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

In [8]:
np.union1d(array1, array2)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

# ★ 23. Write a NumPy program to test whether all elements in an array evaluate to True.     
Note: 0 evaluates to False in NumPy.    
    

<img src='https://www.w3resource.com/w3r_images/python-numpy-image-exercise-23.png' width='600' />

In [9]:
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


# 24. Write a NumPy program to test whether any array element along a given axis evaluates to True.     
Note: 0 evaluates to False in NumPy.    

In [10]:
array = np.array([[True,False,True],[True,True,True]])
array

array([[ True, False,  True],
       [ True,  True,  True]])

In [11]:
print(np.all(array, axis=1))

[False  True]


In [12]:
print(np.all(array, axis=0))

[ True False  True]


In [13]:
np.any(array, axis=1)

array([ True,  True])

# 25. Write a NumPy program to construct an array by repeating.     

```
Sample array: [1, 2, 3, 4]    

Expected Output:    
Original array    
[1, 2, 3, 4]    
Repeating 2 times    
[1 2 3 4 1 2 3 4]    
Repeating 3 times    
[1 2 3 4 1 2 3 4 1 2 3 4]    
    
```    
    


<img src='https://www.w3resource.com/w3r_images/python-numpy-image-exercise-25.png' width='400' />

In [14]:
array = np.array([1, 2, 3, 4])
array

array([1, 2, 3, 4])

In [15]:
np.tile(array, 2)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [16]:
np.tile(array, 3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

# 16. Write a NumPy program to repeat elements of an array.     


```
Expected Output:    
[3 3 3 3]    
[1 1 2 2 3 3 4 4]    
```    
    

In [17]:
x = np.repeat(3, 4)
print(x)
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))

[3 3 3 3]
[1 1 2 2 3 3 4 4]


# ★ 27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.     

```
Original array: [1 2 3 4 5 6]    
Maximum Values: 5    
Minimum Values: 0    
```    
    

<img src='https://www.w3resource.com/w3r_images/python-numpy-image-exercise-27.png'/>

In [18]:
array = np.array(range(1,7))
array

array([1, 2, 3, 4, 5, 6])

In [19]:
np.argmax(array)

5

In [20]:
np.argmin(array)

0

# 28. Write a NumPy program compare two given arrays.     

```
Array a: [1 2]    
Array b: [4 5]    
a > b    
[False False]    
a >= b    
[False False]    
a < b    
[ True True]    
a <= b    
[ True True]    
```    
    

In [21]:
array_a = np.array([1, 2])
array_b = np.array([4, 5])

In [22]:
array_a > array_b

array([False, False])

In [23]:
np.greater(array_a, array_b)

array([False, False])

In [24]:
array_a >= array_b

array([False, False])

In [25]:
np.greater_equal(array_a, array_b)

array([False, False])

In [26]:
array_a < array_b

array([ True,  True])

In [27]:
np.less(array_a, array_b)

array([ True,  True])

In [28]:
array_a <= array_b

array([ True,  True])

In [29]:
np.less_equal(array_a, array_b)

array([ True,  True])

# 29. Write a NumPy program to sort an along the first, last axis of an array.     

```
Sample array: [[4, 6], [2, 1]]   

Expected Output:    
Original array:    
[[4 6]    
[2 1]]    
Sort along the first axis:    
[[2 1]    
[4 6]]    
Sort along the last axis:    
[[1 2]    
[4 6]]    
    
```

In [30]:
array = np.array([[4, 6], [2, 1]])
array

array([[4, 6],
       [2, 1]])

In [31]:
array.sort()

In [32]:
array

array([[4, 6],
       [1, 2]])

In [33]:
array.sort(axis=0)

In [34]:
array

array([[1, 2],
       [4, 6]])

# 30. Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name).     

```
first_names = (Betsey, Shelley, Lanell, Genesis, Margery)    
last_names = (Battle, Brien, Plotner, Stahl, Woolum)    

Expected Output:    
[1 3 2 4 0]    
```    
    

In [35]:
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


In [36]:
print([first_names[i]+' '+last_names[i] for i in x])

['Betsey Battle', 'Lanell Brien', 'Shelley Plotner', 'Genesis Stahl', 'Margery Woolum']


# 31. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.     

```
Original array:    
[[ 0 10 20]    
[20 30 40]]    
Values bigger than 10 = [20 20 30 40]    
Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))    
```

In [37]:
array = np.array([[0, 10, 20], [20, 30, 40]])
array

array([[ 0, 10, 20],
       [20, 30, 40]])

In [39]:
np.where(array>10)

(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [40]:
array[np.where(array>10)]

array([20, 20, 30, 40])

# 32. Write a NumPy program to save a NumPy array to a text file.     
    
    

In [45]:
np.savetxt('text.txt', array, delimiter=',')

In [46]:
!dir text.*

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 50B4-87C1

 C:\Users\N\OneDrive\WorkJ\Machine Learning\Pandas_Numpy\Pandas&Numpy Daily Practice\Numpy 디렉터리

2021-07-24  오전 11:35               152 text.txt
               1개 파일                 152 바이트
               0개 디렉터리  146,962,341,888 바이트 남음


In [50]:
!type text.txt

0.000000000000000000e+00,1.000000000000000000e+01,2.000000000000000000e+01
2.000000000000000000e+01,3.000000000000000000e+01,4.000000000000000000e+01


In [48]:
new_array = np.loadtxt('text.txt',delimiter=',')
new_array

array([[ 0., 10., 20.],
       [20., 30., 40.]])

# 33. Write a NumPy program to find the memory size of a NumPy array.     

Expected Output:    
128 bytes    
    
    

In [51]:
array

array([[ 0, 10, 20],
       [20, 30, 40]])

In [53]:
array.size

6

In [54]:
array.itemsize

4

In [55]:
print('%d bytes'%(array.size * array.itemsize))

24 bytes


<img src='https://www.w3resource.com/w3r_images/python-numpy-image-exercise-33.png' width='300' />

출처: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-33.php

# 34. Write a NumPy program to create an array of ones and an array of zeros.     


```
Expected Output:    
Create an array of zeros    
Default type is float    
[[ 0. 0.]]    

Type changes to int    
[[0 0]]    

Create an array of ones    
Default type is float    
[[ 1. 1.]]    

Type changes to int    
[[1 1]]    
``` 
    

In [56]:
array_0 = np.zeros((2, 1))
array_0

array([[0.],
       [0.]])

In [57]:
array_0.astype('int')

array([[0],
       [0]])

In [58]:
array_1 = np.ones((2, 1))
array_1

array([[1.],
       [1.]])

In [59]:
array_1.astype('int')

array([[1],
       [1]])

# 35. Write a NumPy program to change the dimension of an array.     


```
Expected Output:    
6 rows and 0 columns    
(6,)    
(3, 3) -> 3 rows and 3 columns    
[[1 2 3]    
[4 5 6]    
[7 8 9]]    
Change array shape to (3, 3) -> 3 rows and 3 columns    
[[1 2 3]    
[4 5 6]    
[7 8 9]]    
```    
    

In [60]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)

6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 36. Write a NumPy program to create a contiguous flattened array.     


```
Original array:    
[[10 20 30]    
[20 40 50]]    
New flattened array:    
[10 20 30 20 40 50]    
```

    

In [61]:
array = np.array([[10, 20, 30], [20, 40, 50]])
array

array([[10, 20, 30],
       [20, 40, 50]])

In [62]:
array.flatten()

array([10, 20, 30, 20, 40, 50])

In [63]:
array.ravel()

array([10, 20, 30, 20, 40, 50])

# 37. Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.     


```
Expected Output:    
    
(2, 3)    
int32    
    
```

In [64]:
array = np.random.randint(1,10, (2, 3), dtype='int32')
array

array([[5, 3, 6],
       [7, 9, 1]])

In [65]:
array.shape

(2, 3)

In [67]:
array.dtype

dtype('int32')

# 38. Write a NumPy program to create a new shape to an array without changing its data.     

```
Reshape 3x2:    
[[1 2]    
[3 4]    
[5 6]]    

Reshape 2x3:    
[[1 2 3]    
[4 5 6]]    
``` 
    

In [68]:
array = np.arange(1, 7)
array

array([1, 2, 3, 4, 5, 6])

In [69]:
array.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
array.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

# 39. Write a NumPy program to change the data type of an array.     

```
Expected Output:    
[[ 2 4 6]    
[ 6 8 10]]    
Data type of the array x is: int32    
New Type: float64    
[[ 2. 4. 6.]    
[ 6. 8. 10.]]    
```    
    


In [71]:
array = np.array([[2, 4, 6], [6, 8, 10]])
array

array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [72]:
array.astype('float64')

array([[ 2.,  4.,  6.],
       [ 6.,  8., 10.]])

# 40. Write a NumPy program to create a new array of 3*5, filled with 2.     

Expected Output:    
[[2 2 2 2 2]    
[2 2 2 2 2]    
[2 2 2 2 2]]    
[[2 2 2 2 2]    
[2 2 2 2 2]    
[2 2 2 2 2]]    
    
    

In [73]:
np.full((3, 5), 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])