<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


In [1]:
import numpy as np

출처: https://www.w3resource.com/python-exercises/numpy/index-array.php

# 41. Write a NumPy program to create an array of 10's with the same shape and type of a given array.    

Sample array: x = np.arange(4, dtype=np.int64)    
```
Expected Output:    
[10 10 10 10]    
```
    
   

In [2]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 10)

array([10, 10, 10, 10], dtype=int64)

# 42. Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere.     

```
Expected Output:    

[[ 1. 0. 0.]    
[ 0. 1. 0.]    
[ 0. 0. 1.]]
```
    
    

In [3]:
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 43. Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere. 

```
Expected Output:    

[[4 0 0 0]    
[0 5 0 0]    
[0 0 6 0]    
[0 0 0 8]]    
```
    
    

In [5]:
np.diag([4, 5, 6, 8])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

# 44. Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50.     

```
Expected Output:    

Array from 0 to 50:    
[ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24    
25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]    

Array from 10 to 50:    
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34    
35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```
    
    

In [6]:
np.arange(0, 50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [7]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 45. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.     

```
Expected Output:    
[ 2.5 2.63793103 2.77586207 2.9137931 3.05172414 3.18965517    
.................    
5.81034483 5.94827586 6.0862069 6.22413793 6.36206897 6.5 ]
```
    
    

In [8]:
np.linspace(2.5, 6.5, 30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

# 46. Write a NumPy program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.     
Expected Output:    
[ 100. 141.25375446 199.5262315 281.83829313    
......................    
25118.8643151 35481.33892336 50118.72336273 70794.57843841]    
    
    

In [9]:
np.logspace(2., 5, 20, endpoint=False)

array([  100.        ,   141.25375446,   199.5262315 ,   281.83829313,
         398.10717055,   562.34132519,   794.32823472,  1122.0184543 ,
        1584.89319246,  2238.72113857,  3162.27766017,  4466.83592151,
        6309.5734448 ,  8912.50938134, 12589.25411794, 17782.79410039,
       25118.8643151 , 35481.33892336, 50118.72336273, 70794.57843841])

# 47. Write a NumPy program to create an array which looks like below array.     

Expected Output:    
```
[[ 0.  0.  0.]                                                         
 [ 1.  0.  0.]                                                         
 [ 1.  1.  0.]                                                         
 [ 1.  1.  1.]]
```


In [10]:
np.tri(4, 3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

# 48. Write a NumPy program to create an array which looks like below array.     
Expected Output:    
[[ 2 3 4]    
[ 5 6 7]    
[ 0 9 10]    
[ 0 0 13]]    
    
    

In [11]:
array = np.arange(2, 14).reshape(4, -1)
array[2, 0] = 0
array[3, :2] = 0
array

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 0,  9, 10],
       [ 0,  0, 13]])

In [12]:
np.triu(np.arange(2,14).reshape(4,3), -1)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 0,  9, 10],
       [ 0,  0, 13]])

# 49. Write a NumPy program to collapse a 3-D array into one dimension array.     
Expected Output:    
3-D array:    
[[ 1. 0. 0.]    
[ 0. 1. 0.]    
[ 0. 0. 1.]]    
One dimension array:    
[ 1. 0. 0. 0. 1. 0. 0. 0. 1.]    
    
    

In [14]:
array = np.identity(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
array.flatten()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

# 50. Write a NumPy program to find the 4th element of a specified array.     
Expected Output:    
[[ 2 4 6]    
[ 6 8 10]]    
Forth e1ement of the array:    
6    
    
    

In [18]:
array = np.array([[2, 4, 6], [6, 8, 10]])
array.flatten()[3]

6

# 51. Write a NumPy program to interchange two axes of an array.     
Sample array: [[1 2 3]]    
Expected Output:    
[[1]    
[2]    
[3]]    
    
    

In [19]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

In [20]:
array[:, np.newaxis]

array([[1],
       [2],
       [3]])

# 52. Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.     

```
Expected Output:    

(3, 4, 2)    
(4, 2, 3)
```
    
    

In [23]:
array = np.random.randn(3, 4, 2)
array.shape

(3, 4, 2)

In [25]:
array = array.reshape(4, 2, -2)
array.shape

(4, 2, 3)

# 53. Write a NumPy program to move the specified axis backwards, until it lies in a given position.  

```
Move the following 3rd array axes to first position.    
(2,3,4,5)    

Sample Expected Output:    
(2, 5, 3, 4)
```
    
    

In [33]:
array = np.random.randn(2, 3, 4, 5)
print(array.shape)
array

(2, 3, 4, 5)


array([[[[ 0.70037843, -1.71672169,  0.22707499, -0.00324036,
          -1.01524051],
         [ 1.54393748,  0.86998006, -0.72325482,  0.2547817 ,
          -0.0907239 ],
         [ 0.05882129,  0.71095023, -0.41961498, -1.34090297,
           0.33598358],
         [-1.04755814,  1.40359159,  0.73611775,  0.11380312,
           0.62240422]],

        [[ 0.93147781, -1.21787683,  0.62693074,  0.5156263 ,
           1.65327056],
         [ 0.08127813,  0.63173796, -0.14454266,  1.61409595,
          -0.73958553],
         [ 0.50258097, -0.19677437,  0.28731995,  0.38939452,
          -0.98903655],
         [-0.95695294,  0.79809487, -1.46181055, -1.65450962,
          -0.34324949]],

        [[ 0.24122336, -0.30454582, -0.59563052,  0.6020165 ,
          -0.5153001 ],
         [ 0.00579827, -1.37679732,  0.77908091,  0.32221288,
           0.64411437],
         [ 1.65843982,  1.90516663, -0.05738901,  1.04245687,
           1.20546131],
         [ 1.00918175,  0.28402939, -2.15196077,  

In [34]:
array_trans = array.reshape(2, 5, 3, -1)
array_trans

array([[[[ 0.70037843, -1.71672169,  0.22707499, -0.00324036],
         [-1.01524051,  1.54393748,  0.86998006, -0.72325482],
         [ 0.2547817 , -0.0907239 ,  0.05882129,  0.71095023]],

        [[-0.41961498, -1.34090297,  0.33598358, -1.04755814],
         [ 1.40359159,  0.73611775,  0.11380312,  0.62240422],
         [ 0.93147781, -1.21787683,  0.62693074,  0.5156263 ]],

        [[ 1.65327056,  0.08127813,  0.63173796, -0.14454266],
         [ 1.61409595, -0.73958553,  0.50258097, -0.19677437],
         [ 0.28731995,  0.38939452, -0.98903655, -0.95695294]],

        [[ 0.79809487, -1.46181055, -1.65450962, -0.34324949],
         [ 0.24122336, -0.30454582, -0.59563052,  0.6020165 ],
         [-0.5153001 ,  0.00579827, -1.37679732,  0.77908091]],

        [[ 0.32221288,  0.64411437,  1.65843982,  1.90516663],
         [-0.05738901,  1.04245687,  1.20546131,  1.00918175],
         [ 0.28402939, -2.15196077,  0.78458106, -0.68574108]]],


       [[[ 1.19177332,  0.15552209, -0.0984

# 54. Write a NumPy program to convert specified inputs to arrays with at least one dimension.  

```
Expected Output:    

[ 12.]    
[[ 0. 1. 2.]    
[ 3. 4. 5.]]    
[array([1]), array([3, 4])]    
```
    
    

In [39]:
np.atleast_1d(12.0)

array([12.])

In [41]:
np.atleast_2d([[0, 1, 2],[3, 4, 5]])

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
np.atleast_1d(np.array([1]), np.array([3, 4]))

[array([1]), array([3, 4])]

# 55. Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.     

```
Expected Output:    

View inputs as arrays with at least two dimensions:    
[10]    
[[ 0. 1.]    
[ 2. 3.]]    

View inputs as arrays with at least three dimensions:    
[[[15]]]    
[[[ 0.]    
[ 1.]    
[ 2.]]]
```
    
    

In [43]:
x = 10
print("View inputs as arrays with at least two dimensions:")
print(np.atleast_1d(x))
x = np.arange(4.0).reshape(2, 2)
print(np.atleast_1d(x))
print("View inputs as arrays with at least three dimensions:")
x =15
print(np.atleast_3d(x))
x = np.arange(3.0)
print(np.atleast_3d(x))

View inputs as arrays with at least two dimensions:
[10]
[[0. 1.]
 [2. 3.]]
View inputs as arrays with at least three dimensions:
[[[15]]]
[[[0.]
  [1.]
  [2.]]]


# 56. Write a NumPy program to insert a new axis within a 2-D array. 


2-D array of shape (3, 4).    

```
Expected Output:    
New shape will be will be (3, 1, 4).    
```
    
    

In [50]:
array = np.atleast_2d(np.random.randint(1, 10, (3, 4)))
print(array.shape)
array

(3, 4)


array([[7, 3, 2, 8],
       [8, 3, 7, 2],
       [2, 9, 9, 1]])

In [52]:
array2 = array[:, np.newaxis,:]
array2

array([[[7, 3, 2, 8]],

       [[8, 3, 7, 2]],

       [[2, 9, 9, 1]]])

다른 답안

In [56]:
x = np.zeros((3, 4))
y = np.expand_dims(x, axis=1).shape
print(y)

(3, 1, 4)


# 57. Write a NumPy program to remove single-dimensional entries from a specified shape.     

```
Specified shape: (3, 1, 4)    

Expected Output: (3, 4)    
```
    
    

In [54]:
array2.shape

(3, 1, 4)

In [55]:
array2.reshape(3, 4).shape

(3, 4)

다른 답안

In [59]:
x = np.zeros((3, 1, 4))
print(np.squeeze(x).shape)
np.squeeze(x)

(3, 4)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 58. Write a NumPy program to concatenate two 2-dimensional arrays.    

```
Expected Output:    

Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]   

Expected Output:    
[[ 0 1 3 0 2 4]    
[ 5 7 9 6 8 10]]    
```
    
    

In [63]:
array = np.array([[0, 1, 3], [5, 7, 9]])
array2 = ([[0, 2, 4], [6, 8, 10]])
array, array2 

(array([[0, 1, 3],
        [5, 7, 9]]),
 [[0, 2, 4], [6, 8, 10]])

In [67]:
np.concatenate([array, array2], axis=1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

# 59. Write a NumPy program to convert 1-D arrays as columns into a 2-D array.     

```
Sample array: (10,20,30), (40,50,60)   

Expected Output:    
[[10 40]    
[20 50]    
[30 60]]  
```
    
    

In [68]:
array1 = np.array([10, 20, 30])
array2 = np.array([40, 50, 60])
array1, array2

(array([10, 20, 30]), array([40, 50, 60]))

In [73]:
np.concatenate([array1.reshape(3,-1), array2.reshape(3, -1)], axis = 1)

array([[10, 40],
       [20, 50],
       [30, 60]])

다른 방법

In [74]:
np.column_stack((array1, array2))

array([[10, 40],
       [20, 50],
       [30, 60]])

# 60. Write a NumPy program to convert (in sequence depth wise (along third axis)) two 1-D arrays into a 2-D array.     

```
Sample array: (10,20,30), (40,50,60)    

Expected Output:    
[[[10 40]]    
[[20 50]]    
[[30 60]]]    
```
    

In [75]:
array1 = np.array([[10, 20, 30]])
array2 = np.array([[40, 50, 60]])
array1, array2

(array([[10, 20, 30]]), array([[40, 50, 60]]))

In [76]:
array1.reshape(3,-1)

array([[10],
       [20],
       [30]])

In [78]:
np.dstack((array1.reshape(3, -1), array2.reshape(3, -1)))

array([[[10, 40]],

       [[20, 50]],

       [[30, 60]]])

In [79]:
a = np.array((10,20,30))
b = np.array((40,50,60))
c = np.column_stack((a, b))
print(c)

[[10 40]
 [20 50]
 [30 60]]
