<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


출처: https://www.w3resource.com/python-exercises/numpy/index-array.php

#    
21. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.     

```
Array1: [ 0 10 20 40 60 80]    
Array2: [10, 30, 40, 50, 70]    

Unique values that are in only one (not both) of the input arrays:    
[ 0 20 30 50 60 70 80]    
```
    
    

# 22. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.     

```
Array1: [ 0 10 20 40 60 80]    
Array2: [10, 30, 40, 50, 70]    

Unique sorted array of values that are in either of the two input arrays:    
[ 0 10 20 30 40 50 60 70 80]    
```
    

# 23. Write a NumPy program to test whether all elements in an array evaluate to True.     
Note: 0 evaluates to False in NumPy.    
    

# 24. Write a NumPy program to test whether any array element along a given axis evaluates to True.     
Note: 0 evaluates to False in NumPy.    

# 25. Write a NumPy program to construct an array by repeating.     

```
Sample array: [1, 2, 3, 4]    

Expected Output:    
Original array    
[1, 2, 3, 4]    
Repeating 2 times    
[1 2 3 4 1 2 3 4]    
Repeating 3 times    
[1 2 3 4 1 2 3 4 1 2 3 4]    
    
```    
    


# 16. Write a NumPy program to repeat elements of an array.     


```
Expected Output:    
[3 3 3 3]    
[1 1 2 2 3 3 4 4]    
```    
    

# 27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.     

```
Original array: [1 2 3 4 5 6]    
Maximum Values: 5    
Minimum Values: 0    
```    
    

# 28. Write a NumPy program compare two given arrays.     

```
Array a: [1 2]    
Array b: [4 5]    
a > b    
[False False]    
a >= b    
[False False]    
a < b    
[ True True]    
a <= b    
[ True True]    
```    
    

# 29. Write a NumPy program to sort an along the first, last axis of an array.     

```
Sample array: [[2,5],[4,4]]    

Expected Output:    
Original array:    
[[4 6]    
[2 1]]    
Sort along the first axis:    
[[2 1]    
[4 6]]    
Sort along the last axis:    
[[1 2]    
[4 6]]    
    
```

# 30. Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name).     

```
first_names = (Betsey, Shelley, Lanell, Genesis, Margery)    
last_names = (Battle, Brien, Plotner, Stahl, Woolum)    

Expected Output:    
[1 3 2 4 0]    
```    
    

# 31. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.     

```
Original array:    
[[ 0 10 20]    
[20 30 40]]    
Values bigger than 10 = [20 20 30 40]    
Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))    
```

# 32. Write a NumPy program to save a NumPy array to a text file.     
    
    

# 33. Write a NumPy program to find the memory size of a NumPy array.     

Expected Output:    
128 bytes    
    
    

# 34. Write a NumPy program to create an array of ones and an array of zeros.     


```
Expected Output:    
Create an array of zeros    
Default type is float    
[[ 0. 0.]]    
Type changes to int    
[[0 0]]    
Create an array of ones    
Default type is float    
[[ 1. 1.]]    
Type changes to int    
[[1 1]]    
``` 
    

# 35. Write a NumPy program to change the dimension of an array.     


```
Expected Output:    
6 rows and 0 columns    
(6,)    
(3, 3) -> 3 rows and 3 columns    
[[1 2 3]    
[4 5 6]    
[7 8 9]]    
Change array shape to (3, 3) -> 3 rows and 3 columns    
[[1 2 3]    
[4 5 6]    
[7 8 9]]    
```    
    

# 36. Write a NumPy program to create a contiguous flattened array.     


```
Original array:    
[[10 20 30]    
[20 40 50]]    
New flattened array:    
[10 20 30 20 40 50]    
```

    

# 37. Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.     


```
Expected Output:    
    
(2, 3)    
int32    
    
```

# 38. Write a NumPy program to create a new shape to an array without changing its data.     

```
Reshape 3x2:    
[[1 2]    
[3 4]    
[5 6]]    

Reshape 2x3:    
[[1 2 3]    
[4 5 6]]    
``` 
    

# 39. Write a NumPy program to change the data type of an array.     

```
Expected Output:    
[[ 2 4 6]    
[ 6 8 10]]    
Data type of the array x is: int32    
New Type: float64    
[[ 2. 4. 6.]    
[ 6. 8. 10.]]    
```    
    


# 40. Write a NumPy program to create a new array of 3*5, filled with 2.     

Expected Output:    
[[2 2 2 2 2]    
[2 2 2 2 2]    
[2 2 2 2 2]]    
[[2 2 2 2 2]    
[2 2 2 2 2]    
[2 2 2 2 2]]    
    
    