<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


출처: https://www.w3resource.com/python-exercises/numpy/index-array.php

# 41. Write a NumPy program to create an array of 10's with the same shape and type of a given array.    

Sample array: x = np.arange(4, dtype=np.int64)    
```
Expected Output:    
[10 10 10 10]    
```
    
   

# 42. Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere.     

```
Expected Output:    

[[ 1. 0. 0.]    
[ 0. 1. 0.]    
[ 0. 0. 1.]]
```
    
    

# 43. Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere. 

```
Expected Output:    

[[4 0 0 0]    
[0 5 0 0]    
[0 0 6 0]    
[0 0 0 8]]    
```
    
    

# 44. Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50.     

```
Expected Output:    

Array from 0 to 50:    
[ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24    
25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]    

Array from 10 to 50:    
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34    
35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```
    
    

# 45. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.     

```
Expected Output:    
[ 2.5 2.63793103 2.77586207 2.9137931 3.05172414 3.18965517    
.................    
5.81034483 5.94827586 6.0862069 6.22413793 6.36206897 6.5 ]
```
    
    

# 46. Write a NumPy program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.     
Expected Output:    
[ 100. 141.25375446 199.5262315 281.83829313    
......................    
25118.8643151 35481.33892336 50118.72336273 70794.57843841]    
    
    

# 47. Write a NumPy program to create an array which looks like below array.     
Expected Output:    
[[ 0. 0. 0.]    
...........    
[ 1. 1. 1.]]    
    
    

# 48. Write a NumPy program to create an array which looks like below array.     
Expected Output:    
[[ 2 3 4]    
[ 5 6 7]    
[ 0 9 10]    
[ 0 0 13]]    
    
    

# 49. Write a NumPy program to collapse a 3-D array into one dimension array.     
Expected Output:    
3-D array:    
[[ 1. 0. 0.]    
[ 0. 1. 0.]    
[ 0. 0. 1.]]    
One dimension array:    
[ 1. 0. 0. 0. 1. 0. 0. 0. 1.]    
    
    

# 50. Write a NumPy program to find the 4th element of a specified array.     
Expected Output:    
[[ 2 4 6]    
[ 6 8 10]]    
Forth e1ement of the array:    
6    
    
    

# 51. Write a NumPy program to interchange two axes of an array.     
Sample array: [[1 2 3]]    
Expected Output:    
[[1]    
[2]    
[3]]    
    
    

# 52. Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.     

```
Expected Output:    

(3, 4, 2)    
(4, 2, 3)
```
    
    

# 53. Write a NumPy program to move the specified axis backwards, until it lies in a given position.  

```
Move the following 3rd array axes to first position.    
(2,3,4,5)    

Sample Expected Output:    
(2, 5, 3, 4)
```
    
    

# 54. Write a NumPy program to convert specified inputs to arrays with at least one dimension.  

```
Expected Output:    

[ 12.]    
[[ 0. 1. 2.]    
[ 3. 4. 5.]]    
[array([1]), array([3, 4])]    
```
    
    

# 55. Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.     

```
Expected Output:    

View inputs as arrays with at least two dimensions:    
[10]    
[[ 0. 1.]    
[ 2. 3.]]    

View inputs as arrays with at least three dimensions:    
[[[15]]]    
[[[ 0.]    
[ 1.]    
[ 2.]]]
```
    
    

# 56. Write a NumPy program to insert a new axis within a 2-D array. 


2-D array of shape (3, 4).    

```
Expected Output:    
New shape will be will be (3, 1, 4).    
```
    
    

# 57. Write a NumPy program to remove single-dimensional entries from a specified shape.     

```
Specified shape: (3, 1, 4)    

Expected Output: (3, 4)    
```
    
    

# 58. Write a NumPy program to concatenate two 2-dimensional arrays.    

```
Expected Output:    

Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]   

Expected Output:    
[[ 0 1 3 0 2 4]    
[ 5 7 9 6 8 10]]    
```
    
    

# 59. Write a NumPy program to convert 1-D arrays as columns into a 2-D array.     

```
Sample array: (10,20,30), (40,50,60)   

Expected Output:    
[[10 40]    
[20 50]    
[30 60]]  
```
    
    

# 60. Write a NumPy program to convert (in sequence depth wise (along third axis)) two 1-D arrays into a 2-D array.     

```
Sample array: (10,20,30), (40,50,60)    

Expected Output:    
[[[10 40]]    
[[20 50]]    
[[30 60]]]    
```
    