<a href='https://github.com/SeWonKwon' ><div> <img src ='https://slid-capture.s3.ap-northeast-2.amazonaws.com/public/image_upload/6556674324ed41a289a354258718280d/964e5a8b-75ad-41fc-ae75-0ca66d06fbc7.png' align='left' /> </div></a>


출처: https://www.w3resource.com/python-exercises/numpy/index-array.php

# 61. Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.   

Expected Output:    

```
Original array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]    

After splitting:    
[array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]    
```
    
    

# 62. Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis.     

```
Sample array :    
[[ 0 1 2 3]    
........    
[12 13 14 15]]    

Expected Output:    
[array([[ 0, 1],    
[ 4, 5],    
[ 8, 9],    
[12, 13]]), array([[ 2, 3],    
[ 6, 7],    
[10, 11],    
[14, 15]]), array([], shape=(4, 0), dtype=int64)]    
```
    
    

# 63. Write a NumPy program to get the number of nonzero elements in an array.     


Expected Output:    

```
Original array:    
[[ 0 10 20]    
[20 30 40]]    

Number of non zero elements in the above array:    
5    
```
    
    

# 64. Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.     

```
Original array:    
[[ 0. 0. 0. 0. 0.]    
.........    
[ 0. 0. 0. 0. 0.]]    

Row values ranging from 0 to 4.    
[[ 0. 1. 2. 3. 4.]    
..........    
[ 0. 1. 2. 3. 4.]]    
```
    
    

# 65. Write a NumPy program to test whether specified values are present in an array.     

Expected Output:    

```
Original array:    
[[ 1.12 2. 3.45]    
[ 2.33 5.12 6. ]]    
True    
False    
True    
False    
True    
```
    
    
    

# 66. Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded.     

Expected Output:    
```
[ 0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455    
0.63636364 0.72727273 0.81818182 0.90909091]    
```
    
    

# 67. Write a NumPy program to make an array immutable (read-only).     


Expected Output:    

```
Test the array is read-only or not:    
Try to change the value of the first element:    
Traceback (most recent call last):    
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in    
x[0] = 1    
ValueError: assignment destination is read-only    
    
```
    

# 68. Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100.     

```
Expected Output:    
[ 3 5 6 9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51 54    
55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]    
2318    
```
    
    

# 69. Write a NumPy program to create an array with 10^3 elements.     

```
Expected Output:    
[ 0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 10. 11.    
12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.    
24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.    
- - - - - - - - - - - - - - - - -    
972. 973. 974. 975. 976. 977. 978. 979. 980. 981. 982. 983.    
984. 985. 986. 987. 988. 989. 990. 991. 992. 993. 994. 995.    
996. 997. 998. 999.]    
```
    
    

# 70. Write a NumPy program to create display every element of a NumPy array.     

```
Expected Output:    
0 1 2 3 4 5 6 7 8 9 10 11    
```
    
    
    

# 71. Write a NumPy program to create and display every element of a NumPy array in Fortran order.     

```
Expected Output:    

Elements of the array in Fortan array:    
0 4 8 1 5 9 2 6 10 3 7 11    
    
```    
    
    

# 72. Write a NumPy program to create a 5x5x5 cube of 1's.     

```
Expected Output:    

[[[1 1 1 1 1]    
[1 1 1 1 1]    
[1 1 1 1 1]    
[1 1 1 1 1]    
[1 1 1 1 1]]    
............    
[[1 1 1 1 1]    
[1 1 1 1 1]    
[1 1 1 1 1]    
[1 1 1 1 1]    
[1 1 1 1 1]]]    
```
    
    

# 73. Write a NumPy program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.     

```
Expected Output:    

Original array elements:    
[[ 0 1 2 3]    
[ 4 5 6 7]    
[ 8 9 10 11]]    

New array elements:    
[[ 0 3 6 9]    
[12 15 18 21]    
[24 27 30 33]]    
```
    
    

74. Write a NumPy program to combine a one and a two dimensional array together and display their elements.     

```
Expected Output:    

One dimensional array:    
[0 1 2 3]    

Two dimensional array:    
[[0 1 2 3]    
[4 5 6 7]]    
0:0    
1:1    
2:2    
3:3    
0:4    
1:5    
2:6    
3:7    
```
    
    

# 75. Write a NumPy program to create an array of zeros and three column types (integer, float, character).     

```
Expected Output:    

[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')    
(3, 3., b'Gertrude B. Elion')]    
```
    
    

# 76. Write a NumPy program to create a function cube which cubes all the elements of an array.     

```
Expected Output:    
[ 1 8 27]    
```
    
    

# 77. Write a NumPy program to create an array of (3, 4) shape and convert the array elements in smaller chunks.     

```
Expected Output:    

Original array elements:    
[[ 0 1 2 3]    
[ 4 5 6 7]    
[ 8 9 10 11]]    
[0 4 8]    
[1 5 9]    
[ 2 6 10]    
[ 3 7 11]    
```
    
    

# 78. Write a NumPy program to create a record array from a (flat) list of arrays.     

```
Sample arrays: [1,2,3,4], ['Red', 'Green', 'White', 'Orange'], [12.20,15,20,40]    

Expected Output:    
(1, 'Red', 12.2)    
(2, 'Green', 15.0)    
(3, 'White', 20.0)    
```
    
    

# 79. Write a NumPy program to generate a generic 2D Gaussian-like array.    
```
Expected Output:    

2D Gaussian-like array:    
[[ 0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818    
0.57375342 0.51979489 0.44822088 0.36787944]    
..........    
[ 0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818    
0.57375342 0.51979489 0.44822088 0.36787944]]    
```
    
    
    

# 80. Write a NumPy program to convert a NumPy array into Python list structure.     

```
Expected Output:    

Original array elements:    
[[0 1]    
[2 3]    
[4 5]]    
Array to list:    
[[0, 1], [2, 3], [4, 5]]    
```
    